% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{setspace}
\usepackage{float}
\usepackage{amsmath}
\usepackage{underscore}
\usepackage{float}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Vignette: Simulation studies with ValidationExplorer},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Vignette: Simulation studies with \texttt{ValidationExplorer}}
\author{}
\date{\vspace{-2.5em}2025-10-15}

\begin{document}
\maketitle
\begin{abstract}
Our vignette demonstrates the use of the \texttt{ValidationExplorer} package to conduct statistical simulation studies that can aid in the design phase of bioacoustic studies. In particular, our package facilitates exploration of the costs and inferential properties (e.g., coverage and interval widths) of alternative validation designs in the context of the count detection model framework. Our functions allow the user to specify a suite of candidate validation designs using either a stratified sampling procedure or a fixed-effort design type. An example of the former is provided in the manuscript entitled `\texttt{ValidationExplorer}: Streamlined simulations to provide bioacoustic study design guidance in the presence of misclassification', which was submitted to the Applications series of \emph{Methods in Ecology and Evolution}. In this vignette, we provide further details not covered in the manuscript and an additional example of data simulation, model fitting, and visualization of simulation results when using a fixed-effort design type. Our demonstration here is intended to aid researchers and others to tailor a validation design that provides useful inference while also ensuring that the level of effort meets cost constraints. \vfill
\end{abstract}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\textbf{Disclaimer:} This draft manuscript is distributed solely for the purposes of scientific peer review. Its content is deliberative and pre-decisional, so it must not be disclosed or released by reviewers. Because the manuscript has not yet been approved for publication by the U.S. Geological Survey (USGS), it does not represent any official USGS funding or policy. Any use of trade, firm, or product names is for descriptive purposes only and does not imply endorsement by the U.S. Government.

\newpage

\setcounter{tocdepth}{4}
\tableofcontents

\newpage

\doublespacing

\section{Introduction}\label{introduction}

Automated recording units (ARUs) provide one of the main data sources for many contemporary ecological studies that aim to provide inference about status and trends for assemblages of species (Loeb et al. 2015). As described in the main text, entitled, ``\texttt{ValidationExplorer}: Streamlined simulations to provide bioacoustic study design guidance in the presence of misclassification,'' substantial practical interest lies in identifying cost-effective validation designs that will allow a study to obtain its measurable objectives. We believe that statistical simulation studies are a valuable tool for informing study design -- including the validation step -- prior to gathering ARU data, and it is our goal for \texttt{ValidationExplorer} to provide those tools in an approachable package.

This vignette aids exploration of possible validation designs within a count-detection framework using the \texttt{ValidationExplorer} package. As described in the main text, a validation design is composed of two parts: a random mechanism for selecting observations to be manually reviewed by experts (``validated''), and a percentage or proportion that controls the number of validated recordings. We refer to the random mechanism as the \emph{design type} and the proportion as the level of validation effort (LOVE). In the following section we consider five possible LOVEs and show an example of a fixed effort design.

We emphasize that results from any simulation study -- including those produced using the \texttt{ValidationExplorer} package -- are conditional on the settings and assumptions of the study. In the case of the count-detection model framework that is implemented in \texttt{ValidationExplorer}, the assumptions are

\begin{enumerate}
  \item  The occurrence of species within a site are independent; the presence of one species carries no information about the presence or absence of another.
  \item For any one species, its occurrence at one location is independent of its occurrence at any other location (independence across sites).
  \item Visits to a site (i.e., detector nights) are independent. 
  \item Recordings within the same site-visit are independent.
  \item Each recording is assigned a single species autoID.
  \item Validation of one recording does not influence the probability that another will be validated.
  \item At sites where at least one species is present, the count of recordings generated by each species per night is a Poisson random variable.
  \item All species in the assemblage can co-occur and are capable of being confused (no structural zeros in the classification matrix). 
  \item The configuration of visits to sites is balanced. Note that this is not required to use our method but it is assumed in the simulation studies. For example, the data used by Oram et al. (in submission) had a varying number of detector nights at each site. To model these data, Oram et al. (in submission) made the additional assumption that the number of visits to a site is independent of the presence/absence and expected relative activity of species there. That is, locations where detectors were deployed for more nights were not more or less likely than other sites to be occupied by species of interest and were not more or less likely than other sites to have high levels of activity. 
  \item The fitted model is the same as the model that generated the data.
\end{enumerate}

\noindent Under these assumptions, we outline the step-by-step use of \texttt{ValidationExplorer} in the following section.

\section{\texorpdfstring{Conducting a simulation study with a fixed effort design type \label{FEEx}}{Conducting a simulation study with a fixed effort design type }}\label{conducting-a-simulation-study-with-a-fixed-effort-design-type}

\subsection{What is a fixed effort design?}\label{what-is-a-fixed-effort-design}

In this section, we assume a fixed-effort design type, under which \(x\%\) of recordings obtained from each visit to a site are validated by experts. The level of validation effort is controlled by the value of \(x.\) We begin the process of simulating under this design by defining the real-world objectives and constraints we anticipate.

\subsection{\texorpdfstring{Step 0: Define measurable objectives and constraints \label{MO}}{Step 0: Define measurable objectives and constraints }}\label{step-0-define-measurable-objectives-and-constraints}

Recall from the main text that the first step -- before opening R and loading \texttt{ValidationExplorer} -- is to identify and write down the set of measurable objectives that the data will be used for. Suppose that, for this example, the measurable objectives and cost constraints are the same as those in Section 3 of the main text. That is,

\begin{itemize}
  \item The measurable objective is to estimate relative activity parameters (denoted as $\lambda_k$) for each species with 95% coverage and expected posterior interval width less than 3 calls per night.
\item The monitoring program can pay their expert bat biologists to validate at most 4000 recordings. We make the assumption that all recordings are approximately the same cost to validate (i.e., rare species autoIDs are not necessarily more expensive or time consuming than extremely common ones). 
\end{itemize}

Suppose further that the species assemblage is the same as in the main text. That is, we have six species of interest that co-occur. The existing prior knowledge (perhaps from another study) about the relative activity rates and occurrence probabilities for each species are summarized in Table \ref{tab:assemblage}.

\linespread{1}
\begin{table}

\caption{\label{tab:assemblage}Prior knowledge of relative activity rates and occurrence probabilities for the six bat species of interest. These values will be used to simulate data. }
\centering
\begin{tabular}[t]{lrr}
\toprule
Species & $\psi$ & $\lambda$\\
\midrule
Eptesicus fuscus (EPFU) & 0.63 & 5.9\\
Lasiurus cinereus (LACI) & 0.61 & 4.2\\
Lasionycteris noctivagans (LANO) & 0.85 & 14.3\\
Myotis californicus (MYCA) & 0.70 & 6.2\\
Myotis ciliolabrum (MYCI) & 0.24 & 11.9\\
\addlinespace
Myotis evotis (MYEV) & 0.70 & 2.4\\
\bottomrule
\end{tabular}
\end{table}

\linespread{1}

\subsection{Step 1: Installing and loading required packages}\label{step-1-installing-and-loading-required-packages}

Once measurable objectives and constraints are clearly defined, the next step is to load the required packages. For first time users, it may be necessary to install a number of dependencies, as shown by Table 1 in the main text. If you need to install a dependency or update the version, run the following, with \texttt{your\_package\_name\_here} replaced by the name of the package:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"your\_package\_name\_here"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

After installing the necessary packages, load these libraries by calling

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(nimble)}
\FunctionTok{library}\NormalTok{(coda)}
\FunctionTok{library}\NormalTok{(rstan)}
\FunctionTok{library}\NormalTok{(parallel)}
\FunctionTok{library}\NormalTok{(here)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Finally, install and load \texttt{ValidationExplorer} by running

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{devtools}\SpecialCharTok{::}\FunctionTok{install\_github}\NormalTok{(}\AttributeTok{repo =} \StringTok{"j{-}oram/ValidationExplorer"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(ValidationExplorer)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

With \texttt{ValidationExplorer} installed, users have access to all the functions outlined in the table of functions found in Section \ref{BigTable}.

\subsection{\texorpdfstring{Step 2: Simulate data \label{dataSimulation}}{Step 2: Simulate data }}\label{step-2-simulate-data}

The first step in a simulation study is to simulate data under each of the candidate validation designs, which is accomplished with the \texttt{simulate\_validatedData} function in \texttt{ValidationExplorer}. We begin by assigning values for the number of sites, visits, and species, as well as the parameter values in Table \ref{tab:assemblage}, which are existing estimates obtained by Stratton et al. (2022):

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Set the number of sites, species and visits}
\NormalTok{nsites }\OtherTok{\textless{}{-}} \DecValTok{30}
\NormalTok{nspecies }\OtherTok{\textless{}{-}} \DecValTok{6}
\NormalTok{nvisits }\OtherTok{\textless{}{-}} \DecValTok{4}

\NormalTok{psi }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{0.6331}\NormalTok{, }\FloatTok{0.6122}\NormalTok{, }\FloatTok{0.8490}\NormalTok{, }\FloatTok{0.6972}\NormalTok{, }\FloatTok{0.2365}\NormalTok{, }\FloatTok{0.7036}\NormalTok{)}
\NormalTok{lambda }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{5.9347}\NormalTok{, }\FloatTok{4.1603}\NormalTok{, }\FloatTok{14.2532}\NormalTok{, }\FloatTok{6.1985}\NormalTok{, }\FloatTok{11.8649}\NormalTok{, }\FloatTok{2.4050}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Note that by running multiple simulation studies with varying numbers of sites and balanced visits, \texttt{ValidationExplorer} allows users to investigate all elements of the study design prior to data collection. In addition to specifying the numnber of sites and visits and parameter values, \texttt{simulate\_validatedData} requires that the user supply misclassification probabilities in the form of a matrix, subject to the constraint that rows in the matrix sum to one. An easy way to simulate a matrix of probabilities that meet these criteria is to leverage the \texttt{rdirch} function from the \texttt{nimble} package:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Simulate a hypothetical confusion matrix }
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{10092024}\NormalTok{) }
\NormalTok{Theta }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{apply}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\DecValTok{29}\NormalTok{, nspecies) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) \{nimble}\SpecialCharTok{::}\FunctionTok{rdirch}\NormalTok{(}\AttributeTok{alpha =}\NormalTok{ x)\}))}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Note that the above definition of \texttt{Theta} places high values on the diagonal of the matrix, corresponding to a high probability of correct classification. To lower the diagonal values, change the specification of \texttt{diag(29,\ nspecies)} to a smaller value. For example:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{another\_Theta }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{apply}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\DecValTok{5}\NormalTok{, nspecies) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{    nimble}\SpecialCharTok{::}\FunctionTok{rdirch}\NormalTok{(}\AttributeTok{alpha =}\NormalTok{ x)}
\NormalTok{  \}))}
\end{Highlighting}
\end{Shaded}

\linespread{1}

\texttt{another\_Theta} has lower values on the diagonal, and greater off-diagonal values (i.e., higher probability of misclassification). If you have specific values you would like to use for the assumed classification probabilities (e.g., from an experiment), these can be supplied manually:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{manual\_Theta }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FloatTok{0.9}\NormalTok{, }\FloatTok{0.05}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.02}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }
                       \FloatTok{0.01}\NormalTok{, }\FloatTok{0.7}\NormalTok{, }\FloatTok{0.21}\NormalTok{, }\FloatTok{0.05}\NormalTok{, }\FloatTok{0.02}\NormalTok{, }\FloatTok{0.01}\NormalTok{,  }
                       \FloatTok{0.01}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.95}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.01}\NormalTok{,}
                       \FloatTok{0.05}\NormalTok{, }\FloatTok{0.05}\NormalTok{, }\FloatTok{0.03}\NormalTok{, }\FloatTok{0.82}\NormalTok{, }\FloatTok{0.04}\NormalTok{, }\FloatTok{0.01}\NormalTok{,}
                       \FloatTok{0.01}\NormalTok{, }\FloatTok{0.015}\NormalTok{,  }\FloatTok{0.005}\NormalTok{,  }\FloatTok{0.005}\NormalTok{, }\FloatTok{0.95}\NormalTok{, }\FloatTok{0.015}\NormalTok{,}
                       \FloatTok{0.003}\NormalTok{, }\FloatTok{0.007}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\FloatTok{0.04}\NormalTok{, }\FloatTok{0.06}\NormalTok{, }\FloatTok{0.79}\NormalTok{), }
                       \AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{nrow =} \DecValTok{6}\NormalTok{)}

\FunctionTok{print}\NormalTok{(manual\_Theta)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       [,1]  [,2]  [,3]  [,4] [,5]  [,6]
## [1,] 0.900 0.050 0.010 0.010 0.02 0.010
## [2,] 0.010 0.700 0.210 0.050 0.02 0.010
## [3,] 0.010 0.010 0.950 0.010 0.01 0.010
## [4,] 0.050 0.050 0.030 0.820 0.04 0.010
## [5,] 0.010 0.015 0.005 0.005 0.95 0.015
## [6,] 0.003 0.007 0.100 0.040 0.06 0.790
\end{verbatim}

\linespread{1}

If you define the classifier manually, make sure the rows sum to 1 by running

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{all}\NormalTok{(}\FunctionTok{rowSums}\NormalTok{(manual\_Theta) }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\CommentTok{\# want this to return TRUE}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# If the above returns FALSE, see which one is not 1: }
\FunctionTok{rowSums}\NormalTok{(manual\_Theta)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 1 1 1 1 1
\end{verbatim}

\linespread{1}

With the required inputs defined, we can simulate data:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_data }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_validatedData}\NormalTok{(}
    \AttributeTok{n\_datasets =} \DecValTok{10}\NormalTok{, }\CommentTok{\# For demonstration {-}{-} use 50+ for real simulation studies}
    \AttributeTok{nsites =}\NormalTok{ nsites, }
    \AttributeTok{nvisits =}\NormalTok{ nvisits, }
    \AttributeTok{nspecies =}\NormalTok{ nspecies, }
    \AttributeTok{design\_type =} \StringTok{"FixedPercent"}\NormalTok{, }
    \AttributeTok{scenarios =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\FloatTok{0.15}\NormalTok{, }\FloatTok{0.3}\NormalTok{),}
    \AttributeTok{psi =}\NormalTok{ psi, }
    \AttributeTok{lambda =}\NormalTok{ lambda,}
    \AttributeTok{theta =}\NormalTok{ Theta, }
    \AttributeTok{save\_datasets =} \ConstantTok{FALSE}\NormalTok{, }\CommentTok{\# default value is FALSE}
    \AttributeTok{save\_masked\_datasets =} \ConstantTok{FALSE}\NormalTok{, }\CommentTok{\# default value is FALSE}
    \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"Fixed\_Effort"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Note that we specified the design type through the argument \texttt{design\_type\ =\ "FixedPercent"}, with the possible scenarios defined as the vector \texttt{scenarios\ =\ c(0.05,\ 0.1,\ 0.15,\ 0.3)}. These two arguments specify the set of alternative validation designs we will compare in our simulation study. Under the first validation design, 5\% of recordings from each visit to a site are validated, while in the second validation design 10\% of recordings from each visit to a site are validated, and so on.
Additionally, we have assumed that all selected recordings are successfully validated because we have not specified the \texttt{confirmable\_limits} argument, which is \texttt{NULL} by default. If we believed that the probability a randomly selected recording from detector-night \((i,j)\) lies between 0.4 and 0.6 (as in the main manuscript), for example, we would simulate data as follows:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_data\_with\_conf\_limits }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_validatedData}\NormalTok{(}
    \AttributeTok{n\_datasets =} \DecValTok{10}\NormalTok{,}
    \AttributeTok{nsites =}\NormalTok{ nsites, }
    \AttributeTok{nvisits =}\NormalTok{ nvisits, }
    \AttributeTok{nspecies =}\NormalTok{ nspecies, }
    \AttributeTok{design\_type =} \StringTok{"FixedPercent"}\NormalTok{, }
    \AttributeTok{scenarios =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\FloatTok{0.15}\NormalTok{, }\FloatTok{0.3}\NormalTok{),}
    \AttributeTok{psi =}\NormalTok{ psi, }
    \AttributeTok{lambda =}\NormalTok{ lambda,}
    \AttributeTok{theta =}\NormalTok{ Theta, }
    \AttributeTok{confirmable\_limits =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.4}\NormalTok{, }\FloatTok{0.6}\NormalTok{), }\CommentTok{\# specify the range for the confirmability}
    \AttributeTok{save\_datasets =} \ConstantTok{FALSE}\NormalTok{, }
    \AttributeTok{save\_masked\_datasets =} \ConstantTok{FALSE}\NormalTok{, }
    \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"Fixed\_Effort"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

This argument assumes the probability a call can be confirmed varies across site-visits, falling within the specified range; we can see this in the first 10 site-visits from the first dataset simulated under validation scenario 1:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# validation scenario 1, dataset 1}
\NormalTok{sim\_data\_with\_conf\_limits}\SpecialCharTok{$}\NormalTok{masked\_dfs[[}\DecValTok{1}\NormalTok{]][[}\DecValTok{1}\NormalTok{]] }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(site, visit) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{prop\_confirmable =} \FunctionTok{unique}\NormalTok{(prop\_confirmable)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{print}\NormalTok{(}\AttributeTok{n =} \DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'site'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 120 x 3
## # Groups:   site [30]
##     site visit prop_confirmable
##    <int> <int>            <dbl>
##  1     1     1            0.496
##  2     1     2            0.440
##  3     1     3            0.566
##  4     1     4            0.486
##  5     2     1            0.426
##  6     2     2            0.556
##  7     2     3            0.511
##  8     2     4            0.429
##  9     3     1            0.513
## 10     3     2            0.493
## # i 110 more rows
\end{verbatim}

\linespread{1}

We continue our demonstration using the \texttt{sim\_data} object, which assumes that all selected recordings can be confirmed.

To understand the output from \texttt{simulate\_validatedData}, we can investigate \texttt{sim\_data}. The output is a list, containing three objects:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(sim\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "full_datasets" "zeros"         "masked_dfs"
\end{verbatim}

\linespread{1}

We examine each of these objects below:

\begin{itemize}
\tightlist
\item
  \texttt{full\_datasets}: A list of length \texttt{n\_datasets} with unmasked datasets. These are the datasets under complete validation so that every recording has an autoID and a true species label. We opted to not save these datasets to the working directory by setting \texttt{save\_datasets\ =\ FALSE}. If we had specified \texttt{save\_datasets\ =\ TRUE}, then these will be saved individually in \texttt{directory} as \texttt{dataset\_n.rds}, where \texttt{n} is the dataset number. As an example of one element in \texttt{sim\_data\$full\_datasets}, we examine the third simulated full dataset:
\end{itemize}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{full\_dfs }\OtherTok{\textless{}{-}}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{full\_datasets}
\FunctionTok{head}\NormalTok{(full\_dfs[[}\DecValTok{3}\NormalTok{]]) }\CommentTok{\# Dataset number 3 if all recordings were validated}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 10
## # Groups:   site, visit [1]
##    site visit true_spp id_spp lambda   psi  theta     z count    Y.
##   <int> <int>    <int>  <int>  <dbl> <dbl>  <dbl> <int> <int> <int>
## 1     1     1        1      1   5.93 0.633 0.954      1     4    24
## 2     1     1        1      1   5.93 0.633 0.954      1     4    24
## 3     1     1        1      1   5.93 0.633 0.954      1     4    24
## 4     1     1        1      1   5.93 0.633 0.954      1     4    24
## 5     1     1        4      2   6.20 0.697 0.0289     1     1    24
## 6     1     1        3      3  14.3  0.849 0.826      1    10    24
\end{verbatim}

\linespread{1}

Notice that in addition to the site, visit, true species and autoID (\texttt{id\_spp}) columns, the parameter values (\texttt{lambda}, \texttt{psi}, and \texttt{theta}) are given for each true species-autoID combination. In addition, the occupancy state \texttt{z} for the true species is given and the \texttt{count} of calls at that site visit with a specific true species-autoID label combination. For example, at site 1, visit 1, there are four calls from species 1 that are assigned autoID 1, yielding 4 rows with \texttt{count\ =\ 4}. There is also one call from species 4 that was assigned a species 2 label with probability 0.02893559. Because this happened once, it is documented with \texttt{count\ =\ 1} and only occupies a single row. Next, we can see that there were 10 calls that were correctly identified as species 3; ten rows will have \texttt{true\_spp\ =\ 3} and \texttt{autoID\ =\ 3}. Finally, the \texttt{Y.} column tells us how many observations were made from all species at that site visit; for visit 1 to site 1, the unique value is 24. That is, the 25th row of this dataset will contain the first observation from visit 2 to site 1.

\begin{itemize}
\tightlist
\item
  \texttt{zeros}: A list of length \texttt{n\_datasets} containing the true species-autoID combinations that were never observed at each site visit. These zero counts are necessary for the model to identify occurrence probabilities and relative activity rates. The \texttt{count} column, which, again, contains the count of each site-visit-true\_spp-id\_spp combination, is zero for all entries. For example, in dataset 3 (below), species 2 was not present at site 1, so it could not be classified as species 1 (first row). Additionally, species 3 was present at site 1, but it was never classified as species 1 on visit 1 (second row). If \texttt{save\_datasets\ =\ TRUE}, the zeros for each dataset will also be saved in \texttt{directory} individually as \texttt{zeros\_in\_dataset\_n.rds}, where \texttt{n} is the dataset number.
\end{itemize}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{zeros }\OtherTok{\textless{}{-}}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros}

\CommentTok{\# The site{-}visit{-}true\_spp{-}autoID combinations that were never observed in}
\CommentTok{\# dataset 3. Notice that count = 0 for all rows! }
\FunctionTok{head}\NormalTok{(zeros[[}\DecValTok{3}\NormalTok{]]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 10
## # Groups:   site, visit [1]
##    site visit true_spp id_spp lambda   psi   theta     z count    Y.
##   <int> <int>    <int>  <int>  <dbl> <dbl>   <dbl> <int> <int> <int>
## 1     1     1        2      1   4.16 0.612 0.0286      0     0    24
## 2     1     1        3      1  14.3  0.849 0.0137      1     0    24
## 3     1     1        4      1   6.20 0.697 0.0426      1     0    24
## 4     1     1        5      1  11.9  0.236 0.00559     0     0    24
## 5     1     1        6      1   2.40 0.704 0.00312     1     0    24
## 6     1     1        1      2   5.93 0.633 0.0159      1     0    24
\end{verbatim}

\linespread{1}

\begin{itemize}
\tightlist
\item
  \texttt{masked\_dfs}: A nested list containing each dataset masked under each scenario. For example, \texttt{masked\_dfs{[}{[}4{]}{]}{[}{[}3{]}{]}} contains dataset 3, assuming that it was validated according to scenario 4 (30\% of recordings randomly sampled from each site-visit for validation). If \texttt{save\_masked\_datasets\ =\ TRUE}, then each dataset/scenario combination is saved individually in \texttt{directory} as \texttt{dataset\_n\_masked\_under\_scenario\_s.rds}, where \texttt{n} is the dataset number and \texttt{s} is the scenario number.
\end{itemize}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{masked\_dfs }\OtherTok{\textless{}{-}}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs}

\CommentTok{\# View dataset 3 subjected to the validation design in scenario 4: }
\CommentTok{\# randomly select and validate 30\% of recordings from the first visit }
\CommentTok{\# to each site }
\FunctionTok{head}\NormalTok{(masked\_dfs[[}\DecValTok{4}\NormalTok{]][[}\DecValTok{3}\NormalTok{]], }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 13
##     site visit true_spp id_spp lambda   psi  theta     z count    Y. selected
##    <int> <int>    <int>  <int>  <dbl> <dbl>  <dbl> <int> <int> <int>    <dbl>
##  1     1     1       NA      1   5.93 0.633 0.954      1     4    24        0
##  2     1     1       NA      1   5.93 0.633 0.954      1     4    24        0
##  3     1     1       NA      1   5.93 0.633 0.954      1     4    24        0
##  4     1     1       NA      1   5.93 0.633 0.954      1     4    24        0
##  5     1     1       NA      2   6.20 0.697 0.0289     1     1    24        0
##  6     1     1        3      3  14.3  0.849 0.826      1    10    24        1
##  7     1     1        3      3  14.3  0.849 0.826      1    10    24        1
##  8     1     1        3      3  14.3  0.849 0.826      1    10    24        1
##  9     1     1       NA      3  14.3  0.849 0.826      1    10    24        0
## 10     1     1        3      3  14.3  0.849 0.826      1    10    24        1
## # i 2 more variables: unique_call_id <chr>, scenario <int>
\end{verbatim}

\linespread{1}

The name of this nested list comes from the way that validation effort is simulated: recordings that are not selected for validation have their \texttt{true\_spp} label masked with an \texttt{NA}. Notice that in the example output, all entries in the dataset are identical to the unmasked version output in \texttt{full\_dfs} above, with the exception of the \texttt{true\_spp} column. From this column we can see that calls 1-5 and 9 were not selected for validation (because \texttt{true\_spp\ =\ NA}), while recordings 6-8 and 10 were (because the true species label is not marked as \texttt{NA}).

\subsubsection{\texorpdfstring{Summarize validation effort \label{summarizeEffort}}{Summarize validation effort }}\label{summarize-validation-effort}

For most simulations, it will be useful to summarize the number of recordings that are validated under a given validation design and scenario. This can be accomplished using the \texttt{summarize\_n\_validated} function:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summarize\_n\_validated}\NormalTok{(}
  \AttributeTok{data\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs, }
  \AttributeTok{theta\_scenario =} \StringTok{"1"}\NormalTok{, }
  \AttributeTok{scenario\_numbers =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 4
##   theta_scenario scenario n_selected n_validated
##   <chr>          <chr>         <dbl>       <dbl>
## 1 1              1              218.        218.
## 2 1              2              375.        375.
## 3 1              3              540.        540.
## 4 1              4             1021.       1021.
\end{verbatim}

\linespread{1}

We can see here that any of the validation designs considered in our simulations will remain well within budget.

\subsection{\texorpdfstring{Step 3: MCMC tuning \label{tune}}{Step 3: MCMC tuning }}\label{step-3-mcmc-tuning}

Running a complete simulation study can be time consuming. In an effort to help users improve the efficiency of their simulations, we provide the \texttt{tune\_mcmc} function, which outputs information about possible values for the warmup and total number of iterations required for the MCMC to reach approximate convergence. This function takes in a masked dataset and the corresponding zeros, fits a model to these data, and outputs an estimated run time for 10,000 iterations, as well as the estimated number of required warmup and total iterations. These are intended to assist tuning of the MCMC algorithm, which is done by the user in the following steps, which we walk through in greater detail below:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Use \texttt{tune\_mcmc} to fit a model with multiple long chains.
\item
  Create trace plots for all model parameters.
\item
  Examine effective sample sizes \(n_\text{eff}\) and Gelman-Rubin statistics \(\hat{R}\) for all parameters.
\item
  Choose values for the number of iterations and warmup that are slightly larger than what is needed based on steps 1-3. This may help ensure that a greater number of model fits are available to inform simulation study results.
\end{enumerate}

\subsubsection{Fit a model}\label{fit-a-model}

As in the main text, we use a dataset from the scenario with the lowest number of validated recordings, as we expect the greatest number of iterations for this scenario. In our example, this is scenario 1 , in which an average of \(\approx 218\) recordings are validated per dataset (Section \ref{summarizeEffort}).

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scenario\_number }\OtherTok{\textless{}{-}} \DecValTok{1}
\NormalTok{dataset\_number }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(masked\_dfs[[scenario\_number]]), }\DecValTok{1}\NormalTok{)}

\NormalTok{tune\_list }\OtherTok{\textless{}{-}} \FunctionTok{tune\_mcmc}\NormalTok{(}
  \AttributeTok{dataset =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs[[scenario\_number]][[dataset\_number]], }
  \AttributeTok{zeros =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros[[dataset\_number]] }
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Fitting MCMC in parallel ... this may take a few minutes"
\end{verbatim}

\linespread{1}

The output from \texttt{tune\_mcmc} is a list containing draws from the fitted model, the time required to fit the model with 10,000 draws, MCMC diagnostics and guesses for the number of iterations and warmup required to reliably fit a model. If the guessed values for total iterations and/or warmup are greater than 10,000 draws, an error is issued. We can see the names for each object by running the following block:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(tune\_list)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "max_iter_time"    "min_warmup"       "min_iter"         "fit"             
## [5] "MCMC_diagnostics"
\end{verbatim}

\linespread{1}

The first element is the time required to fit a model with three chains of 10,000 iterations each:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{max\_iter\_time}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Time difference of 2.106008 mins
\end{verbatim}

\linespread{1}

This may seem insignificant, but over the course of an entire simulations study with 5 scenarios \(\times\) 50 datasets, that corresponds to around 8 hours of run time. Using fewer than 10,000 iterations will substantially reduce the time to run a simulation study.

\subsubsection{Create trace plots}\label{create-trace-plots}

To decide the number of iterations and warmup for use in a simulation study, we recommend beginning by creating trace plots, which show how the sampled values of a parameter evolve over the course of each Markov chain. To ensure the MCMC algorithm will characterize the posterior distribution well, we need to check that chains are stationary and mixing well, and that effective sample sizes are sufficiently large to characterize the posterior. Trace plots are especially useful for assessing the first of these. To create a trace plot using the bayesplot package (Gabry et al. 2019) for a single parameter, run the following:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load bayesplot package specifically designed for visualizing }
\FunctionTok{library}\NormalTok{(bayesplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## This is bayesplot version 1.13.0
\end{verbatim}

\begin{verbatim}
## - Online documentation and vignettes at mc-stan.org/bayesplot
\end{verbatim}

\begin{verbatim}
## - bayesplot theme set to bayesplot::theme_default()
\end{verbatim}

\begin{verbatim}
##    * Does _not_ affect other ggplot2 plots
\end{verbatim}

\begin{verbatim}
##    * See ?bayesplot_theme_set for details on theme setting
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# extract the fitted model from tune\_mcmc output}
\NormalTok{fit }\OtherTok{\textless{}{-}}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{fit}

\CommentTok{\# create traceplot}
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{pars =} \StringTok{"lambda[5]"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/unnamed-chunk-6-1.pdf}}

\linespread{1}

We can see that far fewer than 10,000 iterations are likely required because the chains are mixing well after a few hundred iterations. This is shown by strongly overlapping chains, with no one chain appearing by itself in a region of the parameter space. Chains also appear to be stationary because they do not wander vertically substantially after the first few hundred iterations.

We need to check that chains are stationary and mixing for all parameters. One way to accelerate visual inspection this is through the \texttt{regex\_pars} argument, which shows relative activity parameters for all species as in the following three code blocks.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/unnamed-chunk-7-1.pdf}}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"psi"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/unnamed-chunk-8-1.pdf}}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create a traceplot for all elements of the confusion matrix}
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"theta"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/unnamed-chunk-9-1.pdf}}

\linespread{1}

In all of the trace plots for all of the parameters, chains appear to mix quickly, meaning that it is possible a far smaller number of iterations may be suitable for a simulation study. A good place to start for reducing the number of iterations is from the output given by \texttt{tune\_mcmc}. In our case, we can see that a guess for the minimum number of iterations is 1500 with a warmup of 500:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1500
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 500
\end{verbatim}

\linespread{1}

It is possible to use these values to zoom in on the trace plots by using the \texttt{window} argument:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{, }\AttributeTok{window =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/unnamed-chunk-11-1.pdf}}

\linespread{1}

Once again, we see the three chains overlap strongly after around 500 iterations and sample around a horizontal line.

After making traceplots and zooming in for all parameters (not all plots are shown here), it appears that the guessed warmup value of 500 output from \texttt{tune\_mcmc} is a reasonable choice. Even so, we increase our iterations and warmup beyond these minimum values in Section \ref{runSims} to avoid simulations failing due to convergence.

\subsubsection{Examine effective sample size and Gelman-Rubin statistics}\label{examine-effective-sample-size-and-gelman-rubin-statistics}

As a final step, we examine the effective sample sizes (out of 10,000 draws) and \(\hat{R}\) values. The effective sample size statistics \texttt{ess\_bulk} and \texttt{ess\_tail} are MCMC diagnostic statistics that summarizes the number of effectively independent draws from a parameter's posterior distribution the Markov chain contains. If a parameter has a large value in the \texttt{ess\_bulk} column, then it is likely that inference based on sampled draws will characterize the center of the posterior distribution well. The \texttt{ess\_tail} column, on the other hand, describes how much information is available about posterior tail probabilities. Once again, we want a large value for \texttt{ess\_tail}, preferably \texttt{ess\_tail}\(\geq 250\).

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{MCMC\_diagnostics}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      parameter  ess_bulk  ess_tail      Rhat
## 1    lambda[1]  3652.833  3842.057 1.0004734
## 2    lambda[2]  2750.985  4142.610 1.0011381
## 3    lambda[3]  2456.986  3734.300 1.0018069
## 4    lambda[4]  2315.239  3248.090 1.0007142
## 5    lambda[5]  3369.841  4551.674 1.0004723
## 6    lambda[6]  1552.975  2584.210 1.0041167
## 7       psi[1] 17843.526 13524.155 1.0000543
## 8       psi[2] 28758.888 25688.555 1.0001134
## 9       psi[3] 27669.924 20494.567 1.0000498
## 10      psi[4] 28574.243 28125.529 0.9999674
## 11      psi[5] 22555.696 18768.003 1.0003461
## 12      psi[6] 16678.753 14580.508 0.9999894
## 13 theta[1, 1]  3089.094  3431.730 1.0015298
## 14 theta[2, 1]  1149.231  1431.616 1.0003176
## 15 theta[3, 1]  2086.236  3102.648 1.0006715
## 16 theta[4, 1]  3545.432  3889.687 1.0005159
## 17 theta[5, 1]  1891.734  2423.632 1.0017353
## 18 theta[6, 1]  2450.192  2716.723 1.0010108
## 19 theta[1, 2]  2906.504  3254.957 1.0015810
## 20 theta[2, 2]  2203.377  4886.417 1.0003739
## 21 theta[3, 2]  4093.066  6249.036 1.0007785
## 22 theta[4, 2]  3538.335  4624.488 1.0010025
## 23 theta[5, 2]  5145.200  5372.697 1.0003821
## 24 theta[6, 2]  4184.095  4920.899 1.0002691
## 25 theta[1, 3]  2313.864  2674.948 1.0005237
## 26 theta[2, 3]  3239.680  3034.828 1.0006608
## 27 theta[3, 3]  2241.844  4835.208 1.0028867
## 28 theta[4, 3]  2959.951  4163.822 1.0004457
## 29 theta[5, 3]  6861.277  8334.091 1.0001215
## 30 theta[6, 3]  2589.459  3679.968 1.0007771
## 31 theta[1, 4]  2048.866  1204.909 1.0009725
## 32 theta[2, 4]  3409.988  3978.396 1.0001149
## 33 theta[3, 4]  1980.197  4174.414 1.0021819
## 34 theta[4, 4]  3032.871  2898.975 1.0016038
## 35 theta[5, 4]  1203.607  2441.877 1.0048051
## 36 theta[6, 4]  1295.749  1391.426 1.0033014
## 37 theta[1, 5]  3086.749  3607.457 1.0001512
## 38 theta[2, 5]  3120.859  2173.733 1.0005774
## 39 theta[3, 5]  3424.629  3834.745 1.0014128
## 40 theta[4, 5]  4715.617  6019.621 1.0008962
## 41 theta[5, 5]  2216.898  2979.210 1.0026332
## 42 theta[6, 5]  2925.934  3276.139 1.0002864
## 43 theta[1, 6]  2291.364  3308.429 1.0009070
## 44 theta[2, 6]  2434.749  3874.116 1.0010930
## 45 theta[3, 6]  2579.278  3053.958 1.0022487
## 46 theta[4, 6]  1737.276  1611.287 1.0008843
## 47 theta[5, 6]  2171.780  3155.274 1.0014308
## 48 theta[6, 6]  1404.691  1876.026 1.0021353
\end{verbatim}

\linespread{1}

For all parameters, the bulk and tail effective sample sizes are fairly large, meaning that even with fewer than 10,000 draws, we could expect \(n_\text{eff} \geq 250,\) allowing us to characterize both the center and tails of the posteriors for all parameters with these draws. Furthermore, the \(\hat{R}\) values for all parameters is near 1. In general, we want values of \(\hat{R} \leq 1.1\) for chains to be considered converged. We can double check by recomputing these statistics on shortened chains:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# for each chain, extract iterations 1001:2500 for all parameters}
\NormalTok{shortened }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(fit, }\ControlFlowTok{function}\NormalTok{(x) x[}\DecValTok{1001}\SpecialCharTok{:}\DecValTok{2500}\NormalTok{,])}

\CommentTok{\# summarize the shortened chains and select the effective sample }
\CommentTok{\# size columns. mcmc\_sum is an internal function used inside of \textasciigrave{}run\_sims\textasciigrave{}, but}
\CommentTok{\# we use it here to quickly obtain MCMC diagnostics for each parameter}
\FunctionTok{mcmc\_sum}\NormalTok{(shortened, }\AttributeTok{truth =} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(shortened[[}\DecValTok{1}\NormalTok{]]))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(parameter, ess\_bulk, ess\_tail, Rhat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      parameter  ess_bulk  ess_tail      Rhat
## 1    lambda[1]  614.0422  930.3016 1.0014194
## 2    lambda[2]  348.6845  418.6563 1.0113280
## 3    lambda[3]  458.4557  771.3754 1.0089621
## 4    lambda[4]  428.2698  741.2270 1.0057759
## 5    lambda[5]  876.2685 1066.2240 1.0045589
## 6    lambda[6]  165.2617  501.6739 1.0285472
## 7       psi[1] 4594.6789 4355.5565 0.9996716
## 8       psi[2] 4103.1525 4687.6401 0.9997501
## 9       psi[3] 4706.3686 4650.5016 1.0001915
## 10      psi[4] 4330.9840 4434.7997 1.0005300
## 11      psi[5] 4468.5877 4503.1142 0.9999862
## 12      psi[6] 4061.6767 4067.4533 1.0006818
## 13 theta[1, 1]  572.7057  749.7406 1.0036352
## 14 theta[2, 1]  133.6898  150.1882 1.0168343
## 15 theta[3, 1]  349.6040  488.3711 1.0105692
## 16 theta[4, 1]  642.8961  898.7264 1.0032524
## 17 theta[5, 1]  320.5836  393.1908 1.0068782
## 18 theta[6, 1]  489.0000  536.3136 1.0074262
## 19 theta[1, 2]  543.2319  621.2939 1.0046851
## 20 theta[2, 2]  242.0677  693.7228 1.0159144
## 21 theta[3, 2]  727.0506  972.4060 1.0014947
## 22 theta[4, 2]  612.7022  769.9539 1.0041127
## 23 theta[5, 2]  929.6433 1093.6283 1.0016859
## 24 theta[6, 2]  698.1964  900.4195 1.0022209
## 25 theta[1, 3]  479.5112  510.6020 1.0126416
## 26 theta[2, 3]  565.9392  750.1502 1.0114967
## 27 theta[3, 3]  380.0587  723.8334 1.0134287
## 28 theta[4, 3]  696.9606  785.5052 1.0045212
## 29 theta[5, 3] 1018.9484 1378.6968 1.0037006
## 30 theta[6, 3]  625.8650  673.0590 1.0068129
## 31 theta[1, 4]  573.3074  583.7141 1.0142796
## 32 theta[2, 4]  597.1800  799.5704 1.0014929
## 33 theta[3, 4]  295.9557  669.5518 1.0199547
## 34 theta[4, 4]  434.6013  401.6381 1.0139239
## 35 theta[5, 4]  194.8098  405.5507 1.0260172
## 36 theta[6, 4]  148.1781  229.8384 1.0249073
## 37 theta[1, 5]  479.6842  582.1151 1.0093127
## 38 theta[2, 5]  602.1597  604.8773 1.0068240
## 39 theta[3, 5]  523.7980  808.3636 1.0049380
## 40 theta[4, 5] 1100.7183 1753.7906 1.0014950
## 41 theta[5, 5]  395.0118  812.2912 1.0072326
## 42 theta[6, 5]  643.8614  734.3879 1.0059643
## 43 theta[1, 6]  381.7236  645.2598 1.0072976
## 44 theta[2, 6]  507.6568  657.2271 1.0042536
## 45 theta[3, 6]  495.2749  617.1615 1.0115585
## 46 theta[4, 6]  229.8595  209.8128 1.0264163
## 47 theta[5, 6]  534.5484  449.9915 1.0023095
## 48 theta[6, 6]  151.1137  244.0691 1.0215569
\end{verbatim}

\linespread{1}

These results appear satisfactory, with effective sample sizes in both the tail and bulk of the posterior distributions of more than 250 and \(\hat{R}\) near 1. Based on the results of MCMC tuning, it appears that using an MCMC with at least 1500 iterations with at least 500 discarded as warmup should to produce good results for our simulation study.

\subsubsection{Set iterations for simulation}\label{set-iterations-for-simulation}

Based on our findings in the MCMC tuning step, we set the number of iterations for simulation to be slightly higher to guard against convergence issues that preclude using a fitted model for inference:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# to be used in the following section }
\NormalTok{iters\_for\_sims }\OtherTok{\textless{}{-}}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{1000}
\NormalTok{warmup\_for\_sims }\OtherTok{\textless{}{-}}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup }\SpecialCharTok{+} \DecValTok{500}
\end{Highlighting}
\end{Shaded}

\linespread{1}

\subsubsection{A note about non-convergence while tuning}\label{a-note-about-non-convergence-while-tuning}

In some instances, we have run \texttt{tune\_mcmc} with a dataset and received a series of error messages that convergence was not reached in under 10,000 iterations. If this persists after trying to fit several other datasets, we have several options:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  We could increase the number of iterations in the simulation study to be above 10,000 -- perhaps to 20,000 and settle for a longer run time of the simulation study.
\item
  We could take this as a sign that the level of effort is insufficient to identify model parameters. In this case, this scenario should not be considered.
\end{enumerate}

In our experience fitting these models, the second option seems to often be the case, and we encourage users to remove scenarios from consideration if models fit during the tuning step do not reach convergence within 10,000 iterations. It is possible that all validation scenarios -- including ones with very large levels of validation effort -- will lead to a lack of convergence if the number of sites and visits are very low, in which case the number of sites and visits should be re-evaluated.

We emphasize that the results from \texttt{tune\_mcmc} are from a single model fit; they are supplied only as guidelines, and we encourage users to increase the number of iterations above the minimum values output from \texttt{tune\_mcmc}. While each model fit will take slightly longer with an increased number of total iterations, this approach may save time in the long run by avoiding the need to re-run simulations.

\subsection{\texorpdfstring{Step 4: Fit models to simulated data \label{runSims}}{Step 4: Fit models to simulated data }}\label{step-4-fit-models-to-simulated-data}

With the simulated dataset and some informed choices about tuning of the MCMC, we use \texttt{run\_sims} to run the simulations:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sims\_output }\OtherTok{\textless{}{-}} \FunctionTok{run\_sims}\NormalTok{(}
         \AttributeTok{data\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs, }
         \AttributeTok{zeros\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros, }
         \AttributeTok{DGVs =} \FunctionTok{list}\NormalTok{(}\AttributeTok{lambda =}\NormalTok{ lambda, }\AttributeTok{psi =}\NormalTok{ psi, }\AttributeTok{theta =}\NormalTok{ Theta), }
         \AttributeTok{theta\_scenario\_id =} \StringTok{"FE"}\NormalTok{, }\CommentTok{\# for "fixed effort"}
         \AttributeTok{parallel =} \ConstantTok{TRUE}\NormalTok{, }
         \AttributeTok{niter =}\NormalTok{ iters\_for\_sims, }
         \AttributeTok{nburn =}\NormalTok{ warmup\_for\_sims,  }
         \AttributeTok{thin =} \DecValTok{1}\NormalTok{,}
         \AttributeTok{save\_fits =} \ConstantTok{TRUE}\NormalTok{, }
         \AttributeTok{save\_individual\_summaries\_list =} \ConstantTok{FALSE}\NormalTok{, }
         \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"Fixed\_Effort"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Beginning scenario 1.
\end{verbatim}

\begin{verbatim}
## 2025-06-09 09:24:05.203718
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 2.
\end{verbatim}

\begin{verbatim}
## 2025-06-09 09:33:18.106209
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 3.
\end{verbatim}

\begin{verbatim}
## 2025-06-09 09:42:38.877877
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 4.
\end{verbatim}

\begin{verbatim}
## 2025-06-09 09:52:05.758827
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\linespread{1}

The output object, \texttt{sims\_output} is a dataframe with summaries of the MCMC draws for each parameter estimated from each dataset under each validation scenario. Summaries include the posterior mean, standard deviation, Naive standard error, Time-series standard error, quantiles for 50\% and 95\% posterior intervals, median, and MCMC diagnostics (Gelman-Rubin statistic, and effective samples sizes in the tails and bulk of the distribution).

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(sims\_output)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1920 obs. of  19 variables:
##  $ parameter     : chr  "lambda[1]" "lambda[2]" "lambda[3]" "lambda[4]" ...
##  $ Mean          : num  6.03 4.82 14.03 6 11.97 ...
##  $ SD            : num  0.349 0.344 0.479 0.477 1.154 ...
##  $ Naive SE      : num  0.0052 0.00512 0.00714 0.00712 0.0172 ...
##  $ Time-series SE: num  0.013 0.0168 0.0195 0.025 0.1687 ...
##  $ 2.5%          : num  5.39 4.2 13.12 5.08 10.33 ...
##  $ 25%           : num  5.79 4.58 13.71 5.66 11.29 ...
##  $ 50%           : num  6.01 4.8 14 6.01 11.79 ...
##  $ 75%           : num  6.24 5.01 14.34 6.32 12.37 ...
##  $ 97.5%         : num  6.8 5.61 14.98 6.94 15.61 ...
##  $ Rhat          : num  1.01 1.01 1.01 1 1.07 ...
##  $ ess_bulk      : num  716 431.3 577.2 388.6 36.7 ...
##  $ ess_tail      : num  986.1 517.1 870.1 702.1 12.2 ...
##  $ truth         : num  5.93 4.16 14.25 6.2 11.86 ...
##  $ capture       : num  1 0 1 1 1 1 1 1 1 1 ...
##  $ converge      : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ theta_scenario: chr  "FE" "FE" "FE" "FE" ...
##  $ scenario      : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ dataset       : int  1 1 1 1 1 1 1 1 1 1 ...
\end{verbatim}

\linespread{1}

Note that we fit all models in parallel to reduce simulation time; we encourage users to do the same. However, if you fit models with \texttt{parallel\ =\ FALSE} in \texttt{run\_sims}, the console will display the messages NIMBLE prints as it compiles code for each model. Internally, we specify a custom distribution to compute the marginal probabilities for ambiguous autoID labels, and you will see a warning about overwriting a custom user-specified distribution if \texttt{parallel\ =\ FALSE}. These warnings can be safely ignored.

\subsection{\texorpdfstring{Step 5: Visualize simulations \label{viz}}{Step 5: Visualize simulations }}\label{step-5-visualize-simulations}

Once models have been fit to all simulated datasets, you can visualize results using several functions. We recommend beginning with the most detailed functions, which are \texttt{visualize\_parameter\_group} and \texttt{visualize\_single\_parameter}. The plots output from these functions show many following features of the simulation study. These are

\begin{itemize}
\tightlist
\item
  Facet grids: parameters (only for \texttt{visualize\_parameter\_group})
\item
  X-axis: Manual verification scenario
\item
  y-axis: parameter values
\item
  Small grey error bars: 95\% posterior interval for an individual model fit where all parameters were below \texttt{convergence\_threshold}.
\item
  Colored error bars: average 95\% posterior interval across all converged models under that scenario.
\item
  Color: Coverage, or the rate at which 95\% posterior intervals contain the true data-generating parameter value.
\item
  Black points: the true value of the parameter
\item
  Red points: average posterior mean
\end{itemize}

The \texttt{visualize\_parameter\_group} function is useful for examining an entire set of parameters, such as all relative activity parameters. For example, we can visualize the inference for the relative activity parameters in the first three scenarios in our simulation study above by running the code below.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_output, }
  \AttributeTok{pars =} \StringTok{"lambda"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{,}
  \AttributeTok{convergence\_threshold =} \FloatTok{1.05}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/vizGroup-1.pdf}}
\caption{\label{fig:vizGroup} Example output from the \texttt{visualize\_parameter\_group} function. Results are faceted by parameter, with the x-axis indicating the validation scenario number, and the y-axis showing the data generating value (black point). Red points show average posterior means, small grey intervals show 95\% posterior intervals from converged model fits and colored intervals are average 95\% posterior intervals. Coverage is shown by color, with blue corresponding to low coverage.}
\end{figure}

\linespread{1}

The output shown in Figure \ref{fig:vizGroup} indicates that under all validation scenarios we considered, the expected inference for relative activity rates of species 1-4 and 6 meets our measurable objectives: the posterior interval width is less than three for these species and there is minimal estimation error. However, note that under validation scenario 1 and 2, fewer of the models converged within 2500 iterations of the MCMC, which is visible from smaller number of grey intervals. This suggests that a higher level of validation effort could be beneficial. Additionally, average interval width is never below 3 for species 5; none of the designs considered here meet the measurable objective for this species. We can see this more clearly by examining output through alternative visualization functions.

A first step would be to use \texttt{visualize\_single\_parameter}, which takes the same arguments as the previous visualization function:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_single\_parameter}\NormalTok{(}
\NormalTok{  sims\_output, }\AttributeTok{par =} \StringTok{"lambda[5]"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{, }
  \AttributeTok{convergence\_threshold =} \FloatTok{1.05}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/vizOne-1.pdf}}
\caption{\label{fig:vizOne}Example output from \texttt{visualize\_single\_parameter} is similar to that of \texttt{visualize\_parameter\_group}: the x-axis shows the validation scenario, and the y-axis shows the true value of the parameter (black point). Average posterior means are shown by red points, individual 95\% posterior intervals from converged model fits are shown as small grey error bars and average 95\% posterior intervals are shown by the larger colored error bars. The coverage is indicated by color.}
\end{figure}

\linespread{1}

The greater detail of \texttt{visualize\_single\_parameter} in Figure \ref{fig:vizOne} underscores the difference in the number of converged models, shown by the number grey 95\% posterior interval for each converged model fit. The visualization also helps clarify that while average interval width is near 3 in scenario 2, it is still acceptable for our measurable objectives. Coverage for most relative activity parameters is also near-nominal under this validation scenario, which requires that around 375 recordings be validated in an average dataset. This can also be seen using the \texttt{plot\_width\_vs\_calls} function (Figure \ref{fig:plotWidth}), which compares average interval widths (and the IQR for interval widths) across scenarios based on the number of recordings validated. An example is provided below:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# obtain summary of validation effort as an object that can be used with }
\CommentTok{\# the summary plot functions plot\_x\_vs\_calls}
\NormalTok{s }\OtherTok{\textless{}{-}}  \FunctionTok{summarize\_n\_validated}\NormalTok{(}
  \AttributeTok{data\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs, }
  \AttributeTok{theta\_scenario =} \StringTok{"FE"}\NormalTok{, }\CommentTok{\# must not be NULL for the plot\_X\_vs\_calls functions}
  \AttributeTok{scenario\_numbers =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_width\_vs\_calls}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_output, }
  \AttributeTok{calls\_summary =}\NormalTok{ s, }
  \AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \StringTok{"FE"}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{2}\SpecialCharTok{:}\DecValTok{5}
\NormalTok{) }\SpecialCharTok{+} \CommentTok{\# add horizontal line at target 95\% CI width }
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{3}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dotted"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/plotWidth-1.pdf}}
\caption{\label{fig:plotWidth}Example output from \texttt{plot\_width\_vs\_calls}. The x-axis shows the number of validated recordings. Note that the level of effort increases with scenario number for the fixed-effort designs; this may not always be the case, for example, with a stratified-by-species design as in the main text. The y-axis shows the value of the average 95\% posterior interval width (point). The middle 50\% of interval widths for each parameter are shown by the error bars. Color indicates the parameter.}
\end{figure}

\linespread{1}

We provide analogous functions \texttt{plot\_coverage\_vs\_calls} and \texttt{plot\_bias\_vs\_calls} taking identical arguments that show how coverage and estimation error change with the number of calls validated. Note that in all of our visualization functions, if no fitted models have \(\hat{R} \leq c\) for all parameters, where \(c\) is the specified convergence threshold under a given scenario, then the scenario will not appear on the x-axis. In our example, we used \(c = 1.1\).

To ensure that there aren't substantial problems with estimation of other model parameters, we can create plots for \(\psi\) and \(\Theta\):

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_output, }
  \AttributeTok{pars =} \StringTok{"psi"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{,}
  \AttributeTok{convergence\_threshold =} \FloatTok{1.05}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/vizPsi-1.pdf}}
\caption{\label{fig:vizPsi}We encourage users to check inference for other model parameters, even if they are not explicitly of interest based on measurable objectives. Here, we examine \(\boldsymbol{\psi}\). Note that coverage for several parameters is slightly low. For the purpose of exposition, we only fit 10 datasets and we expect that coverage would be near nominal levels if 50 or more datasets were used in simulation.}
\end{figure}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_output, }
  \AttributeTok{pars =} \StringTok{"theta"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{,}
  \AttributeTok{convergence\_threshold =} \FloatTok{1.05}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/plotTheta-1.pdf}}
\caption{\label{fig:plotTheta}Checking inference for the elements of the classification matrix \(\Theta\). For most parameters (facets), validation scenario 2 appears to lead to minimal estimation error and near-nominal coverage.}
\end{figure}

\linespread{1}

The simulation results shown in Figure \ref{fig:vizPsi} and \ref{fig:plotTheta} don't immediately cause concern that inference for relative activity rates will be severely compromised for any of these validation designs. Some parameters have slightly low coverage, but we believe this is mostly due to the small number of datasets used in this example; users should increase the number of datasets to at least 50, which we expect would lead to coverage near nominal levels.

\subsection{\texorpdfstring{Take-aways from the Fixed-Effort Simulations \label{takeaway-FE}}{Take-aways from the Fixed-Effort Simulations }}\label{take-aways-from-the-fixed-effort-simulations}

Based on Figures \ref{fig:vizGroup} - \ref{fig:plotWidth}, we can rule out validation scenario 1, because the expected width of 95\% posterior intervals is greater than the threshold value of 3. Because of this, we might choose validation scenario 2 as one possible fixed effort validation design. This fixed effort design assumes that 10\% of recordings from each site-night are randomly selected for validation, leading to around 375 recordings being validated per dataset. In our simulations, posterior means for each \(\lambda_k\) appear to be nearly unbiased, with near-nominal coverage and average posterior interval widths less than or equal to 3 for this scenario. However, it is possible that for a given dataset, the interval width for \(\lambda_5\) will be larger than 3, regardless of the number of validated calls; error bars in Figure \ref{fig:plotWidth} overlap or exceed the dotted line in all scenarios.

In situations such as this one, a decision is required of the user. If a slightly larger interval width is acceptable, validating 10\% percent of recordings from all site-visits is reasonable. If it is not, then the LOVE will need to be increased beyond that in scenario 4 (1021 recordings). The question is whether potentially tripling the number of validated recordings will be worth the benefit of ensuring the relative activity level for species 5 is less than 3. This is a question about measurable objectives that we leave to the practitioner and their study priorities.

\newpage

\section{\texorpdfstring{Stratified-by-species example \label{stratEx}}{Stratified-by-species example }}\label{stratified-by-species-example}

In this section, we provide further details of the example in the main manuscript, which assumed a stratified-by-species design. In a stratified-by-species design, the random mechanism is a stratified random sample, with strata formed by the species labels assigned during automated classification (i.e., by autoID). In this type of design, the LOVE is the proportion of recordings selected to be validated for each species label.

We repeat the simulation study conducted in the main text in this section, providing greater detail for some of the steps. We assume the same measurable objectives as in Section \ref{FEEx}, but we now assume the maximum number of recordings that can be viewed by experts during the validation process is 1000.

\subsection{\texorpdfstring{Simulate data \label{simBySpp}}{Simulate data }}\label{simulate-data}

Using the same values for \texttt{psi}, \texttt{lambda} and \texttt{Theta} as in Section \ref{dataSimulation}, we simulate data using \texttt{simulate\_validatedData} with \texttt{design\_type\ =\ "BySpecies"} and set the probability of successfully validating a selected recording using the \texttt{confirmable\_limits} argument. This will yield simulated data in the format described in Section \ref{dataSimulation}.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_data }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_validatedData}\NormalTok{(}
  \AttributeTok{n\_datasets =} \DecValTok{10}\NormalTok{, }
  \AttributeTok{design\_type =} \StringTok{"BySpecies"}\NormalTok{,}
  \AttributeTok{scenarios =} \FunctionTok{list}\NormalTok{(}
    \AttributeTok{spp1 =} \FloatTok{0.15}\NormalTok{, }
    \AttributeTok{spp2 =} \FloatTok{0.15}\NormalTok{, }
    \AttributeTok{spp3 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.15}\NormalTok{, .}\DecValTok{5}\NormalTok{, }\DecValTok{1}\NormalTok{),}
    \AttributeTok{spp4 =} \FloatTok{0.1}\NormalTok{, }
    \AttributeTok{spp5 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{),}
    \AttributeTok{spp6 =} \FloatTok{0.25}
\NormalTok{  ),}
  \AttributeTok{nsites =}\NormalTok{ nsites, }
  \AttributeTok{nspecies =}\NormalTok{ nspecies, }
  \AttributeTok{nvisits =}\NormalTok{ nvisits,}
  \AttributeTok{psi =}\NormalTok{ psi, }
  \AttributeTok{lambda =}\NormalTok{ lambda, }
  \AttributeTok{theta =}\NormalTok{ Theta, }
  \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"BySpecies"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Note that in contrast with Section \ref{dataSimulation}, \texttt{simulate\_validatedData} expects the \texttt{scenarios} argument to be a list of proportions corresponding to the possible levels of effort for each species when specifying a stratified-by-species design. Internally, \texttt{simulate\_validatedData} calls \texttt{base::expand.grid}, and considers all possible combinations of the various levels of effort for each species, meaning that the number of simulated scenarios grows extremely quickly. The biggest implication of having a larger number of simulation scenarios to consider is increased computation time. For example, in the previous code block we fixed the level of effort for species 1, 2, 4 and 6 at .15, .15, .1, and .25, respectively. There are three possible proportions to validate for species 3 and two possible levels of effort for species 5, yielding six possible scenarios, which are summarized in the additional output \texttt{sim\_data\$scenarios\_df} that is available when \texttt{design\_type\ =\ "BySpecies"} is specified:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(sim\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "full_datasets" "zeros"         "masked_dfs"    "scenarios_df"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_data}\SpecialCharTok{$}\NormalTok{scenarios\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   scenario spp1 spp2 spp3 spp4 spp5 spp6
## 1        1 0.15 0.15 0.15  0.1  0.5 0.25
## 2        2 0.15 0.15 0.50  0.1  0.5 0.25
## 3        3 0.15 0.15 1.00  0.1  0.5 0.25
## 4        4 0.15 0.15 0.15  0.1  1.0 0.25
## 5        5 0.15 0.15 0.50  0.1  1.0 0.25
## 6        6 0.15 0.15 1.00  0.1  1.0 0.25
\end{verbatim}

\linespread{1}

If users would like to supply a tailored set of validation scenarios, this can be done through the \texttt{scen\_expand} and \texttt{scen\_df} arguments as follows:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Define the scenarios dataframe. Each row is a scenario, each column is a spp}
\NormalTok{my\_scenarios }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{spp1 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.05}\NormalTok{, }\FloatTok{0.1}\NormalTok{), }
  \AttributeTok{spp2 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\FloatTok{0.2}\NormalTok{, }\FloatTok{0.3}\NormalTok{),}
  \AttributeTok{spp3 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.2}\NormalTok{, }\FloatTok{0.2}\NormalTok{, }\FloatTok{0.25}\NormalTok{), }
  \AttributeTok{spp4 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.4}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\FloatTok{0.6}\NormalTok{), }
  \AttributeTok{spp5 =} \FunctionTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{), }
  \AttributeTok{spp6 =} \FunctionTok{rep}\NormalTok{(}\FloatTok{0.5}\NormalTok{, }\DecValTok{3}\NormalTok{)}
\NormalTok{)}

\NormalTok{sim\_data2 }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_validatedData}\NormalTok{(}
  \AttributeTok{n\_datasets =} \DecValTok{10}\NormalTok{, }
  \AttributeTok{design\_type =} \StringTok{"BySpecies"}\NormalTok{,}
  \AttributeTok{scen\_expand =} \ConstantTok{FALSE}\NormalTok{, }
  \AttributeTok{scen\_df =}\NormalTok{ my\_scenarios,}
  \AttributeTok{scenarios =} \ConstantTok{NULL}\NormalTok{,}
  \AttributeTok{nsites =}\NormalTok{ nsites, }
  \AttributeTok{nspecies =}\NormalTok{ nspecies, }
  \AttributeTok{nvisits =}\NormalTok{ nvisits,}
  \AttributeTok{psi =}\NormalTok{ psi, }
  \AttributeTok{lambda =}\NormalTok{ lambda, }
  \AttributeTok{theta =}\NormalTok{ Theta, }
  \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"BySpecies"}\NormalTok{)}
\NormalTok{)}

\NormalTok{sim\_data2}\SpecialCharTok{$}\NormalTok{scenarios\_df }\CommentTok{\# the same as my\_scenarios above}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   scenario spp1 spp2 spp3 spp4 spp5 spp6
## 1        1 0.05  0.1 0.20  0.4    1  0.5
## 2        2 0.05  0.2 0.20  0.5    1  0.5
## 3        3 0.10  0.3 0.25  0.6    1  0.5
\end{verbatim}

\linespread{1}

In the remainder of this example, we use the \texttt{sim\_data} object.
We can combine the \texttt{scenarios\_df} output with the output of \texttt{summarize\_n\_validated} to understand what the scenarios are and how many recordings are validated under each.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{summary1 }\OtherTok{\textless{}{-}}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{scenarios\_df}
\NormalTok{summary2 }\OtherTok{\textless{}{-}} \FunctionTok{summarize\_n\_validated}\NormalTok{(}
\NormalTok{  sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs, }
  \AttributeTok{scenario\_numbers =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \StringTok{"BySpecies"}
\NormalTok{)}

\NormalTok{call\_sum }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(summary1, summary2, }\AttributeTok{by =} \StringTok{"scenario"}\NormalTok{)}

\NormalTok{call\_sum}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   scenario spp1 spp2 spp3 spp4 spp5 spp6 theta_scenario n_selected n_validated
## 1        1 0.15 0.15 0.15  0.1  0.5 0.25      BySpecies      603.8       603.8
## 2        2 0.15 0.15 0.50  0.1  0.5 0.25      BySpecies     1018.3      1018.3
## 3        3 0.15 0.15 1.00  0.1  0.5 0.25      BySpecies     1610.4      1610.4
## 4        4 0.15 0.15 0.15  0.1  1.0 0.25      BySpecies      778.3       778.3
## 5        5 0.15 0.15 0.50  0.1  1.0 0.25      BySpecies     1192.8      1192.8
## 6        6 0.15 0.15 1.00  0.1  1.0 0.25      BySpecies     1784.9      1784.9
\end{verbatim}

\linespread{1}

In the resulting dataframe, we see that scenario 1 has the lowest overall level of validation effort: species 1-3 have 15\% of their recordings validated, species 4 has 10\% validated, species 5 has 50\%, and species 6 has 25\%, yielding around 604 recordings validated in an average dataset. We use one dataset simulated under scenario 1 to tune the MCMC.

\subsection{Tune the MCMC}\label{tune-the-mcmc}

The MCMC tuning in this step is very similar to the procedures used in Section \ref{tune}. We begin by fitting a model to one dataset using the \texttt{tune\_mcmc} function.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(sim\_data}\SpecialCharTok{$}\NormalTok{full\_datasets), }\DecValTok{1}\NormalTok{)}

\NormalTok{tune\_list }\OtherTok{\textless{}{-}} \FunctionTok{tune\_mcmc}\NormalTok{(}
  \AttributeTok{dataset =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs[[}\DecValTok{1}\NormalTok{]][[i]],}
  \AttributeTok{zeros =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros[[i]]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Fitting MCMC in parallel ... this may take a few minutes"
\end{verbatim}

\linespread{1}

As in Section \ref{tune}, we visually inspect the chains for convergence using trace plots. We set trace plot windows to be wider than the suggested values from \texttt{tune\_mcmc}, meaning a lower starting value and a higher ending value. Based on these plots, chains appear to be mixing well as no one chain stands out visually.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 500
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1500
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# increase iters to visualize beyond the warmup and }
\CommentTok{\# iterations output from tune\_mcmc }
\NormalTok{fit }\OtherTok{\textless{}{-}}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{fit}

\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{, }\AttributeTok{window =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{500}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/unnamed-chunk-22-1.pdf}}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"psi"}\NormalTok{, }\AttributeTok{window =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{500}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/unnamed-chunk-23-1.pdf}}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"theta"}\NormalTok{, }\AttributeTok{window =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{500}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/unnamed-chunk-24-1.pdf}}

\linespread{1}

In all trace plots, it appears that MCMC chains have reached approximate convergence well before the warmup value of 500 draws output from \texttt{tune\_mcmc}.

Next, we examine the effective sample sizes in the tails and bulk of the posteriors and the \(\hat{R}\) values:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{MCMC\_diagnostics}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      parameter  ess_bulk  ess_tail      Rhat
## 1    lambda[1]  4772.434  5706.252 1.0011652
## 2    lambda[2]  3796.652  5267.398 1.0008436
## 3    lambda[3]  4507.156  5070.928 1.0007154
## 4    lambda[4]  3418.473  4721.196 1.0011603
## 5    lambda[5]  4164.835  5984.111 1.0013020
## 6    lambda[6]  3478.977  5085.051 1.0016735
## 7       psi[1] 30149.016 29747.803 1.0000256
## 8       psi[2] 27172.781 28937.541 1.0001424
## 9       psi[3] 28378.425 29640.022 1.0001165
## 10      psi[4] 29232.492 27998.470 1.0000099
## 11      psi[5] 28231.454 29068.024 0.9999676
## 12      psi[6] 23401.975 25610.785 0.9999816
## 13 theta[1, 1]  5685.753 11143.095 1.0014346
## 14 theta[2, 1]  3476.766  3932.828 1.0004445
## 15 theta[3, 1]  3366.931  2875.985 1.0011051
## 16 theta[4, 1]  5427.704  7350.476 1.0003756
## 17 theta[5, 1]  4199.977  3440.736 1.0019560
## 18 theta[6, 1]  3422.408  3248.514 1.0007115
## 19 theta[1, 2]  3587.106  4725.026 1.0024531
## 20 theta[2, 2]  4508.207  6860.425 1.0007329
## 21 theta[3, 2]  5230.351  5908.190 1.0005163
## 22 theta[4, 2]  3331.923  4665.432 1.0005872
## 23 theta[5, 2]  5591.340  6729.969 1.0002573
## 24 theta[6, 2]  4311.421  4945.338 1.0006196
## 25 theta[1, 3]  4434.987  4353.709 1.0012485
## 26 theta[2, 3]  4273.372  5843.093 1.0007153
## 27 theta[3, 3]  4728.164  7368.557 1.0008673
## 28 theta[4, 3]  4521.507  6301.107 1.0009693
## 29 theta[5, 3]  2788.104  3592.558 1.0012923
## 30 theta[6, 3]  4062.059  5252.014 1.0000728
## 31 theta[1, 4]  3622.632  4045.829 1.0007371
## 32 theta[2, 4]  4040.907  5534.438 1.0008168
## 33 theta[3, 4]  4090.731  5511.251 1.0005607
## 34 theta[4, 4]  5778.815  7264.400 1.0002098
## 35 theta[5, 4]  4631.237  6715.512 1.0004906
## 36 theta[6, 4]  4074.116  5662.092 1.0009292
## 37 theta[1, 5]  7375.902 10371.052 1.0005950
## 38 theta[2, 5]  6027.130  5515.853 1.0009288
## 39 theta[3, 5]  4013.674  4005.220 1.0004770
## 40 theta[4, 5]  7552.174 10320.109 1.0002859
## 41 theta[5, 5]  5179.996  9610.730 1.0004359
## 42 theta[6, 5]  6231.274  6746.832 1.0004136
## 43 theta[1, 6]  3492.462  2999.550 1.0012299
## 44 theta[2, 6]  3299.626  2835.658 1.0004785
## 45 theta[3, 6]  5741.792  8529.094 1.0003734
## 46 theta[4, 6]  5429.122  6320.611 1.0005119
## 47 theta[5, 6]  4489.175  4960.459 1.0010953
## 48 theta[6, 6]  4600.375  7561.754 1.0006706
\end{verbatim}

\linespread{1}

For all parameters, the bulk and tail effective sample sizes are fairly large: if we slightly decrease the number of post-warmup draws, we could expect to characterize both the center and tails of the posteriors well. Additionally, \(\hat{R} \approx 1.00\) for all parameters, indicating good mixing for chains. As before, we check this suspicion by computing MCMC diagnostic statistics for truncated chains:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# for each chain, extract iterations 501:2000 for all parameters}
\NormalTok{shortened }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(fit, }\ControlFlowTok{function}\NormalTok{(x) x[(tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup)}\SpecialCharTok{:}\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{1000}\NormalTok{,])}

\CommentTok{\# summarize the shortened chains and select the effective sample }
\CommentTok{\# size columns}
\FunctionTok{mcmc\_sum}\NormalTok{(shortened, }\AttributeTok{truth =} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(shortened[[}\DecValTok{1}\NormalTok{]]))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(parameter, ess\_bulk, ess\_tail)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      parameter  ess_bulk  ess_tail
## 1    lambda[1]  424.5713  664.6459
## 2    lambda[2]  422.4104  615.3778
## 3    lambda[3]  506.3128  618.9718
## 4    lambda[4]  420.1305  460.6655
## 5    lambda[5]  445.7138  471.4093
## 6    lambda[6]  438.8664  645.7396
## 7       psi[1] 3002.8818 2517.4295
## 8       psi[2] 2677.8741 3009.2043
## 9       psi[3] 2736.1245 2992.5800
## 10      psi[4] 2786.7924 3034.5688
## 11      psi[5] 2908.6486 2966.2673
## 12      psi[6] 2490.0652 2757.3506
## 13 theta[1, 1]  475.1734 1364.9401
## 14 theta[2, 1]  360.7615  377.0463
## 15 theta[3, 1]  517.5116  514.8454
## 16 theta[4, 1]  394.1677  795.1916
## 17 theta[5, 1]  682.6389  861.1382
## 18 theta[6, 1]  355.7301  288.9261
## 19 theta[1, 2]  381.6768  543.0554
## 20 theta[2, 2]  492.9362  978.0086
## 21 theta[3, 2]  481.5445  610.9855
## 22 theta[4, 2]  367.2110  548.1204
## 23 theta[5, 2]  456.6807  810.6579
## 24 theta[6, 2]  422.7855  445.2624
## 25 theta[1, 3]  418.6501  851.7604
## 26 theta[2, 3]  515.9960  668.2527
## 27 theta[3, 3]  514.7494 1188.5949
## 28 theta[4, 3]  434.0378  737.2293
## 29 theta[5, 3]  345.5852  504.8556
## 30 theta[6, 3]  468.2047  833.3336
## 31 theta[1, 4]  317.2759  398.2371
## 32 theta[2, 4]  347.5720  337.4483
## 33 theta[3, 4]  482.7624  543.6476
## 34 theta[4, 4]  498.9000  994.3939
## 35 theta[5, 4]  497.1584  692.5203
## 36 theta[6, 4]  424.3001  632.5707
## 37 theta[1, 5]  801.4883 1046.1417
## 38 theta[2, 5]  658.2086  767.6261
## 39 theta[3, 5]  475.0484  620.0248
## 40 theta[4, 5]  713.7307 1021.8712
## 41 theta[5, 5]  519.4110  937.3165
## 42 theta[6, 5]  632.8519  617.2047
## 43 theta[1, 6]  445.9647  607.8477
## 44 theta[2, 6]  373.0941  338.0811
## 45 theta[3, 6]  597.8016 1208.5917
## 46 theta[4, 6]  538.4026  495.2611
## 47 theta[5, 6]  417.1296  536.9738
## 48 theta[6, 6]  422.2332  841.9593
\end{verbatim}

\linespread{1}

The results appear satisfactory, with effective sample sizes of more than 250 in both the tail and bulk of the posterior distributions for each parameter. Based on the results of MCMC exploration, it appears that using an MCMC with 2500 iterations with 500 discarded as warmup is likely to produce good results for our simulation study.

\subsection{Fit models}\label{fit-models}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sims\_out }\OtherTok{\textless{}{-}} \FunctionTok{run\_sims}\NormalTok{(}
  \AttributeTok{data\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs,}
  \AttributeTok{zeros\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros,}
  \AttributeTok{DGVs =} \FunctionTok{list}\NormalTok{(}\AttributeTok{lambda =}\NormalTok{ lambda, }\AttributeTok{psi =}\NormalTok{ psi, }\AttributeTok{theta =}\NormalTok{ Theta),}
  \AttributeTok{theta\_scenario\_id =} \StringTok{"BySpecies"}\NormalTok{, }
  \AttributeTok{parallel =} \ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{niter =}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{500}\NormalTok{, }
  \AttributeTok{nburn =}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup }\SpecialCharTok{+} \DecValTok{250}\NormalTok{,}
  \AttributeTok{thin =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{save\_fits =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{save\_individual\_summaries\_list =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"BySpecies"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Beginning scenario 1.
\end{verbatim}

\begin{verbatim}
## 2025-10-15 17:30:04.332383
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 2.
\end{verbatim}

\begin{verbatim}
## 2025-10-15 17:40:26.139136
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 3.
\end{verbatim}

\begin{verbatim}
## 2025-10-15 17:50:51.175666
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 4.
\end{verbatim}

\begin{verbatim}
## 2025-10-15 18:01:24.977562
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 5.
\end{verbatim}

\begin{verbatim}
## 2025-10-15 18:11:36.429073
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 6.
\end{verbatim}

\begin{verbatim}
## 2025-10-15 18:21:55.599415
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\linespread{1}

The output, \texttt{sims\_out}, will have the same structure as described in Section \ref{runSims}.

\subsection{\texorpdfstring{Visualize results \label{vizbyspp}}{Visualize results }}\label{visualize-results}

Recall that the measurable objectives of our study are to estimate the relative activity rates with estimation error less than 1 call per night and a 95\% posterior interval width of less than 3 calls per night. Furthermore, we assume that the monitoring program can afford to validate 4000 calls in total. All of the possible validation designs shown in \texttt{sim\_data\$scenarios\_df} are feasible given this budget.

We begin with detailed plots of relative activity rates, occurrence probabilities, and classification probabilities.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_out, }
  \AttributeTok{pars =} \StringTok{"lambda"}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \StringTok{"BySpecies"}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{, }
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/vizLamBySpecies-1.pdf}}
\caption{\label{fig:vizLamBySpecies}Output from \texttt{visualize\_parameter\_group} under six possible stratified-by-species scenarios for relative activity rates. Parameters are shown in each facet and validation scenario number is on the x-axis. Small grey intervals are 95\% posterior intervals for each parameter from fitted models that converged. Larger colored error bars are average 95\% posterior intervals with the color indicating the coverage. Black dots are the true parameter value and red dots are average posterior means.}
\end{figure}

\linespread{1}

Based on the simulation results shown in Figure \ref{fig:vizLamBySpecies}, any of validation scenarios 1-6 is expected to produce a posterior mean estimate for each relative activity parameter that is near the true value. All models converged for all scenarios. Coverage varies by scenario for each parameter, but recall that we only fit models to 10 datasets.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_out, }
  \AttributeTok{pars =} \StringTok{"psi"}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \StringTok{"BySpecies"}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{, }
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/vizPsiBySpecies-1.pdf}}
\caption{\label{fig:vizPsiBySpecies}Output from \texttt{visualize\_parameter\_group} under six possible stratified-by-species scenarios for occurrence probabilities. Parameters are shown in each facet and validation scenario number is on the x-axis. Small grey intervals are 95\% posterior intervals for each parameter from fitted models that converged. Larger colored error bars are average 95\% posterior intervals with the color indicating the coverage. Black dots are the true parameter value and red dots are average posterior means.}
\end{figure}

\linespread{1}

The simulation results for occurrence probabilities show a small amount estimation error for all occurrence probabilities, with the size and direction varying depending on the species. For species with larger estimation error, coverage is also slightly low. However, since we are most concerned with relative activity, the goal is to check results for each \(\psi_k\) for severe estimation error and/or lack of coverage, which are not shown in Figure \ref{fig:vizPsiBySpecies}. Similarly, we do not observe alarming results in Figure \ref{fig:vizThetaBySpecies}.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_out, }
  \AttributeTok{pars =} \StringTok{"theta"}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \StringTok{"BySpecies"}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{, }
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/vizThetaBySpecies-1.pdf}}
\caption{\label{fig:vizThetaBySpecies}Output from \texttt{visualize\_parameter\_group} under six possible stratified-by-species scenarios for classification probabilities. Parameters are shown in each facet and validation scenario number is on the x-axis. Small grey intervals are 95\% posterior intervals for each parameter from fitted models that converged. Larger colored error bars are average 95\% posterior intervals with the color indicating the coverage. Black dots are the true parameter value and red dots are average posterior means.}
\end{figure}

\linespread{1}

One measurable objective is for 95\% posterior interval widths to be less than 3 calls per night for each species' relative activity rate. As in Section \ref{viz}, the \texttt{plot\_width\_vs\_calls} function provides Figure \ref{fig:widthVscalls}, which addresses this measurable objective directly.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_width\_vs\_calls}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_out, }
  \AttributeTok{calls\_summary =}\NormalTok{ call\_sum, }
  \AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \FunctionTok{unique}\NormalTok{(sims\_out}\SpecialCharTok{$}\NormalTok{theta\_scenario),}
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{,}
  \AttributeTok{max\_calls =} \DecValTok{1000} \CommentTok{\# put shading over scenarios that are beyond budget}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio]{Vignette_files/figure-latex/widthVscalls-1.pdf}}
\caption{\label{fig:widthVscalls}Plots of 95\% posterior interval width vs the number of calls validated.}
\end{figure}

\linespread{1}

Once again as in Section \ref{viz}, the widest posterior interval width is for species 5. All validation scenarios have average 95\% posterior interval widths near or slightly below 3 calls per night, but the error bars indicate an interval width greater than 3 is possible for any validation scenario. Scenario 6, in which 1785 recordings are validated, has the narrowest expected interval width.

\subsection{\texorpdfstring{Take-aways \label{takeaway-bySpp}}{Take-aways }}\label{take-aways}

The results in Section \ref{vizbyspp}, imply that, of the stratified-by-species validation designs considered, scenario 6 offered the best results with respect to the measurable objectives we outlined in Section \ref{MO}. In this scenario, the six species in our assemblage receive 15\%, 15\%, 100\%, 10\%, 100\%, and 25\% of their recordings validated, respectively.

To keep the number of scenarios in this example small, we fixed the LOVE for several species. However, if the measurable objectives specified the desired accuracy and precision for estimates of occurrence probability, it may be desirable to consider alternative validation scenarios. For example, we consistently underestimated the occurrence probability for species 6 (Figure \ref{fig:vizPsiBySpecies}), and additional simulations under validation designs that varied the level of effort for species 6 would be warranted if measurable objectives related to occurrence probability for this species.

\section{Conclusion}\label{conclusion}

We have demonstrated the use of the \texttt{ValidationExplorer} package when the objective is to compare the merits of four competing LOVEs for fixed-effort and stratified-by-species designs. Specifically, in the fixed-effort design we considered validating a random sample of 5\%, 10\%, 15\% or 30\% of the recordings obtained during each visit to each site. In the stratified-by-species designs, we considered a suite of validation designs, fixing effort for species 1,2, 4, and 6 at less than or equal to 25\%, and varied the level of effort for species 3 and 5. The exact simulations considered are summarized in the \texttt{call\_sum} object in Section \ref{simBySpp}. The measurable objectives outlined in Section \ref{MO} were to estimate the relative activity parameters for each species, with near-nominal coverage and width less than 3 calls per night for 95\% posterior intervals. Results, and their implications for these measurable objectives were summarized in Sections \ref{takeaway-FE} and \ref{takeaway-bySpp}. Practitioners who would like to inform study design prior to data collection can repeat multiple simulation studies to see how inferences change with the number of sites and balanced visits, in addition to the validation design.

\newpage

\section{\texorpdfstring{Table of Functions \label{BigTable}}{Table of Functions }}\label{table-of-functions}

\singlespacing
\begin{longtable}{p{0.27\linewidth}p{0.32\linewidth}p{0.33\linewidth}}
    \toprule
        Function & Argument & Description   \\
        \midrule
        
        \texttt{simulate\textunderscore validatedData} &  \texttt{n\textunderscore datasets} & The number of datasets to be simulated \\ 
        \addlinespace
        & \texttt{design\textunderscore type} & The type of validation design. Must be one of \texttt{"BySpecies"} or \texttt{"FixedPercent"} \\ 
        \addlinespace
        & \texttt{scenarios} & The possible levels of effort. If \texttt{design\textunderscore type = "BySpecies"}, this is provided as a list with vector-valued entries containing the possible percentages to validate for each species. If \texttt{design\textunderscore type = "FixedPercent"}, this argument is a vector of possible percentages. \\ 
        \addlinespace
        & \texttt{n\textunderscore sites, n\textunderscore visits, n\textunderscore species} & The number of sites, visits and species in the assemblage \\ 
        \addlinespace
        & \texttt{psi, lambda, theta},  & Vectors of length \texttt{nspecies} containing the the parameter values for each species \\ 
        \addlinespace
        & \texttt{directory} & The working directory where datasets are to be saved if the following arguments are set to TRUE \\
        \addlinespace
        & \texttt{save\textunderscore datasets, save\textunderscore masked_datasets} & Logicals indicating whether to save each type of dataset \\
        \addlinespace

        \hline
        \texttt{summarize\textunderscore n\textunderscore validated} & \texttt{data\textunderscore list} & A list of simulated (masked) datasets output from \texttt{simulate\textunderscore validatedData} \\ 
        \addlinespace 
        & \texttt{zeros\textunderscore list} & A list of true species/autoID combinations that were never observed at each site-visit. \\ 
        \addlinespace
        & \texttt{theta\textunderscore scenario} & An optional character string identifying the classifier scenario. If output from \texttt{summarize\textunderscore n\textunderscore validated} is to be used with any of the \texttt{plot\textunderscore X\textunderscore vs\textunderscore calls} functions described below, this string must match the \texttt{theta\textunderscore scenario\textunderscore id} argument supplied to \texttt{run\textunderscore sims}. \\
        \addlinespace

        \hline
        \texttt{run\textunderscore sims} & \texttt{data\textunderscore list} & A nested list of masked datasets in the format output from \texttt{simualate\textunderscore validatedData}. The first layer of the list corresponds to scenarios, with each entry containing a list of \texttt{n\textunderscore datasets} validated according to the scenario. \\ 
        \addlinespace
        & \texttt{zeros\textunderscore list} & A list of length \texttt{n\textunderscore datasets} containing the site-visit-true-autoID combinations that were never observed. \\ 
        \addlinespace 
        & \texttt{DGVs} & A named list of the true data-generating values with entries \texttt{"psi", "lambda"} and \texttt{"theta"}. \\ 
        \addlinespace
        & \texttt{theta\textunderscore scenario\textunderscore id} & An ID to show which classifier the scenario is under. This is provided as a convenience for the user if multiple simulation studies are to be conducted.\\
        \addlinespace
        & \texttt{parallel} &  A logical indicating whether MCMC sampling should be fit in parallel (default setting is TRUE). If you have many datasets and many scenarios, we recommend this setting. \\
        \addlinespace
        & \texttt{n\textunderscore iter, nburn, thin} &  The number of iterations, warmup and thinning interval for each chain in the MCMC. Default values are 2000, 1000, and 1, respectively. \\ 
        \addlinespace
        & \texttt{save\textunderscore fits} &  A logical denoting whether or not to save the draws from individual fitted models. If TRUE, you must have the file structure described in Step 2. Fits will be saved as RDS objects that can be read in later. Default value is FALSE.\\
        \addlinespace
        & \texttt{save\textunderscore individual\textunderscore summaries\textunderscore list} & A logical indicating whether to save individual summary lists that are output after each validation scenario. Default value is FALSE.\\ 
        \addlinespace
        & \texttt{directory} &  Where to save fits and summaries. Required if \texttt{save\textunderscore fits\ =\ TRUE} or \texttt{save\textunderscore individual\textunderscore summaries\textunderscore list\ =\ TRUE}. Default value is the current working directory given by \texttt{here::here()} \\ 
        \addlinespace 

        \hline
    
        \texttt{visualize\textunderscore parameter\textunderscore group} & \texttt{sim\textunderscore summary} & A dataframe in the format of the summaries output by \texttt{run\textunderscore sims}. Column names must match those of the \texttt{run\textunderscore sims} output. \\ 
        \addlinespace 
        & \texttt{pars} & The name of the parameter ``group'' to be visualized (e.g, \texttt{"psi"}, \texttt{"lambda"} or \texttt{"theta"}). \\ 
        \addlinespace 
        & \texttt{theta\textunderscore scenario}&  The \(\Theta\) classifier ID. \\ 
        \addlinespace 
        & \texttt{scenarios} &  Which scenarios to visualize? \\ 
        \addlinespace 
        & \texttt{convergence\textunderscore threshold}& What value should $\hat{R}$ be below to be considered ``converged''? Default value is 1.1. This value matters because only model fits where all parameter values are below the \texttt{convergence\textunderscore threshold} are used for visualization. \\ 
        \addlinespace 
        
        \hline
        \texttt{visualize\textunderscore single\textunderscore parameter} & & Arguments are identical to  \texttt{visualize\textunderscore parameter\textunderscore group} \\ 
        \addlinespace
        
        \hline 
        
        \texttt{plot_bias_vs_calls}, \texttt{plot_coverage_vs_calls}, \texttt{plot_width_vs_calls} & \texttt{sims_summary} & The summary output in the format from \texttt{run\textunderscore sims} \\ 
        \addlinespace
        & \texttt{calls\textunderscore summary} & A summary of the number of calls validated per scenario. Expected format is that of output from \texttt{summarize\textunderscore n\textunderscore validated}. \\ 
        \addlinespace
        & \texttt{pars} & The parameters to visualize. \\ 
        \addlinespace
        & \texttt{regex\textunderscore pars} & A group of parameters to visualize. One of \texttt{"psi"}, \texttt{"lambda"} or \texttt{"theta"}. \\ 
        \addlinespace
        & \texttt{theta\textunderscore scenario} & The classifier scenario ID. \\
        \addlinespace
        & \texttt{scenarios} & The scenarios to be compared. \\
        \addlinespace
        & \texttt{convergence\textunderscore threshold} & At what value is an MCMC algorithm considered ``converged"? \\ 
        \addlinespace
        \bottomrule
    \caption{Argument descriptions for each function in the \texttt{ValidationExplorer} software. My hope is that in the eventual final paper, this will be a scrollable html table}
    \label{tab:my_label}
\end{longtable}

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-bayesplot}
Gabry, Jonah, Daniel Simpson, Aki Vehtari, Michael Betancourt, and Andrew Gelman. 2019. {``Visualization in Bayesian Workflow.''} \emph{J. R. Stat. Soc. A} 182: 389--402. \url{https://doi.org/10.1111/rssa.12378}.

\bibitem[\citeproctext]{ref-loeb15}
Loeb, Susan C., Thomas J. Rodhouse, Laura E. Ellison, Cori L. Lausen, Jonathan D. Reichard, Kathryn M. Irvine, Thomas E. Ingersoll, et al. 2015. {``A Plan for the {N}orth {A}merican Bat Monitoring Program ({NAB}at).''} SRS-208. USDA Forest Service.

\bibitem[\citeproctext]{ref-stratton22}
Stratton, Christian, Kathryn M. Irvine, Katharine M. Banner, Wilson J. Wright, Cori Lausen, and Jason Rae. 2022. {``Coupling Validation Effort with in Situ Bioacoustic Data Improves Estimating Relative Activity and Occupancy for Multiple Species with Cross-Species Misclassifications.''} \emph{Methods in Ecology and Evolution} 13 (6): 1288--1303. https://doi.org/\url{https://doi.org/10.1111/2041-210X.13831}.

\end{CSLReferences}

\end{document}
