% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{setspace}
\usepackage{float}
\usepackage{amsmath}
\usepackage{underscore}
\usepackage{float}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Vignette: Simulation studies with ValidationExplorer},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Vignette: Simulation studies with \texttt{ValidationExplorer}}
\author{}
\date{\vspace{-2.5em}2026-03-16}

\begin{document}
\maketitle
\begin{abstract}
Our vignette demonstrates the use of the \texttt{ValidationExplorer} package to conduct statistical simulation studies that can aid in the design phase of bioacoustic studies. In particular, our package facilitates exploration of the costs and inferential properties (e.g., coverage and interval widths) of alternative validation designs in the context of the count detection model framework. Our functions allow the user to specify a suite of candidate validation designs using either a stratified sampling procedure or a fixed-effort design type. An example of the former is provided in the manuscript entitled `\texttt{ValidationExplorer}: Streamlined simulations to provide bioacoustic study design guidance in the presence of misclassification', which was submitted to the Applications series of \emph{Methods in Ecology and Evolution}. In this vignette, we provide further details not covered in the manuscript and an additional example of data simulation, model fitting, and visualization of simulation results when using a fixed-effort design type. Our demonstration here is intended to aid researchers and others to tailor a validation design that provides useful inference while also ensuring that the level of effort meets cost constraints. \vfill
\end{abstract}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\textbf{Disclaimer:} This draft manuscript is distributed solely for the purposes of scientific peer review. Its content is deliberative and pre-decisional, so it must not be disclosed or released by reviewers. Because the manuscript has not yet been approved for publication by the U.S. Geological Survey (USGS), it does not represent any official USGS funding or policy. Any use of trade, firm, or product names is for descriptive purposes only and does not imply endorsement by the U.S. Government.

\newpage

\setcounter{tocdepth}{4}
\tableofcontents

\newpage

\doublespacing

\section{Introduction}\label{introduction}

Automated recording units (ARUs) provide one of the main data sources for many contemporary ecological studies that aim to provide inference about status and trends for assemblages of species (Loeb et al. 2015). As described in the main text, entitled, ``\texttt{ValidationExplorer}: Streamlined simulations to provide bioacoustic study design guidance in the presence of misclassification,'' substantial practical interest lies in identifying cost-effective validation designs that will allow a study to obtain its measurable objectives. We believe that statistical simulation studies are a valuable tool for informing study design -- including the validation step -- prior to gathering ARU data, and it is our goal for \texttt{ValidationExplorer} to provide those tools in an approachable package.

This vignette aids exploration of possible validation designs within a count-detection framework using the \texttt{ValidationExplorer} package. As described in the main text, a validation design is composed of two parts: a random mechanism for selecting observations to be manually reviewed by experts (``validated''), and a percentage or proportion that controls the number of validated recordings. We refer to the random mechanism as the \emph{design type} and the proportion as the level of validation effort (LOVE). In the following section we consider five possible LOVEs and show an example of a fixed effort design.

We emphasize that results from any simulation study -- including those produced using the \texttt{ValidationExplorer} package -- are conditional on the settings and assumptions of the study. In the case of the count-detection model framework that is implemented in \texttt{ValidationExplorer}, the assumptions are

\begin{enumerate}
  \item  The occurrence of species within a site are independent; the presence of one species carries no information about the presence or absence of another.
  \item For any one species, its occurrence at one location is independent of its occurrence at any other location (independence across sites).
  \item Visits to a site (i.e., detector nights) are independent. 
  \item Recordings within the same site-visit are independent.
  \item Each recording is assigned a single species autoID.
  \item Validation of one recording does not influence the probability that another will be validated.
  \item At sites where at least one species is present, the count of recordings generated by each species per night is a Poisson random variable.
  \item All species in the assemblage can co-occur and are capable of being confused (no structural zeros in the classification matrix). 
  \item The configuration of visits to sites is balanced. Note that this is not required to use our method but it is assumed in the simulation studies. For example, the data used by Oram et al. (in submission) had a varying number of detector nights at each site. To model these data, Oram et al. (in submission) made the additional assumption that the number of visits to a site is independent of the presence/absence and expected relative activity of species there. That is, locations where detectors were deployed for more nights were not more or less likely than other sites to be occupied by species of interest and were not more or less likely than other sites to have high levels of activity. 
  \item The fitted model is the same as the model that generated the data.
\end{enumerate}

\noindent Under these assumptions, we outline the step-by-step use of \texttt{ValidationExplorer} in the following section.

\section{\texorpdfstring{Conducting a simulation study with a fixed effort design type \label{FEEx}}{Conducting a simulation study with a fixed effort design type }}\label{conducting-a-simulation-study-with-a-fixed-effort-design-type}

\subsection{What is a fixed effort design?}\label{what-is-a-fixed-effort-design}

In this section, we assume a fixed-effort design type, under which \(x\%\) of recordings obtained from each visit to a site are validated by experts. The level of validation effort is controlled by the value of \(x.\) We begin the process of simulating under this design by defining the real-world objectives and constraints we anticipate.

\subsection{\texorpdfstring{Step 0: Define measurable objectives and constraints \label{MO}}{Step 0: Define measurable objectives and constraints }}\label{step-0-define-measurable-objectives-and-constraints}

Recall from the main text that the first step -- before opening R and loading \texttt{ValidationExplorer} -- is to identify and write down the set of measurable objectives that the data will be used for. Suppose that, for this example, the measurable objectives and cost constraints are the same as those in Section 3 of the main text. That is,

\begin{itemize}
  \item The measurable objective is to estimate relative activity parameters (denoted as $\lambda_k$) for each species with 95% coverage and expected posterior interval width less than 3 calls per night.
\item The monitoring program can pay their expert bat biologists to validate at most 4000 recordings. We make the assumption that all recordings are approximately the same cost to validate (i.e., rare species autoIDs are not necessarily more expensive or time consuming than extremely common ones). 
\end{itemize}

Suppose further that the species assemblage is the same as in the main text. That is, we have six species of interest that co-occur. The existing prior knowledge (perhaps from another study) about the relative activity rates and occurrence probabilities for each species are summarized in Table \ref{tab:assemblage}.

\linespread{1}
\begin{table}

\caption{\label{tab:assemblage}Prior knowledge of relative activity rates and occurrence probabilities for the six bat species of interest. These values will be used to simulate data. }
\centering
\begin{tabular}[t]{lrr}
\toprule
Species & $\psi$ & $\lambda$\\
\midrule
Eptesicus fuscus (EPFU) & 0.63 & 5.9\\
Lasiurus cinereus (LACI) & 0.61 & 4.2\\
Lasionycteris noctivagans (LANO) & 0.85 & 14.3\\
Myotis californicus (MYCA) & 0.70 & 6.2\\
Myotis ciliolabrum (MYCI) & 0.24 & 11.9\\
\addlinespace
Myotis evotis (MYEV) & 0.70 & 2.4\\
\bottomrule
\end{tabular}
\end{table}

\linespread{1}

\subsection{Step 1: Installing and loading required packages}\label{step-1-installing-and-loading-required-packages}

Once measurable objectives and constraints are clearly defined, the next step is to load the required packages. For first time users, it may be necessary to install a number of dependencies, as shown by Table 1 in the main text. If you need to install a dependency or update the version, run the following, with \texttt{your\_package\_name\_here} replaced by the name of the package:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"your\_package\_name\_here"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

After installing the necessary packages, load these libraries by calling

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(nimble)}
\FunctionTok{library}\NormalTok{(coda)}
\FunctionTok{library}\NormalTok{(rstan)}
\FunctionTok{library}\NormalTok{(parallel)}
\FunctionTok{library}\NormalTok{(here)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Finally, install and load \texttt{ValidationExplorer} by running

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{devtools}\SpecialCharTok{::}\FunctionTok{install\_github}\NormalTok{(}\AttributeTok{repo =} \StringTok{"j{-}oram/ValidationExplorer"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(ValidationExplorer)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

With \texttt{ValidationExplorer} installed, users have access to all the functions outlined in the table of functions found in Section \ref{BigTable}.

\subsection{\texorpdfstring{Step 2: Simulate data \label{dataSimulation}}{Step 2: Simulate data }}\label{step-2-simulate-data}

The first step in a simulation study is to simulate data under each of the candidate validation designs, which is accomplished with the \texttt{simulate\_validatedData} function in \texttt{ValidationExplorer}. We begin by assigning values for the number of sites, visits, and species, as well as the parameter values in Table \ref{tab:assemblage}, which are existing estimates obtained by Stratton et al. (2022):

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Set the number of sites, species and visits}
\NormalTok{nsites }\OtherTok{\textless{}{-}} \DecValTok{30}
\NormalTok{nspecies }\OtherTok{\textless{}{-}} \DecValTok{6}
\NormalTok{nvisits }\OtherTok{\textless{}{-}} \DecValTok{4}

\NormalTok{psi }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{0.6331}\NormalTok{, }\FloatTok{0.6122}\NormalTok{, }\FloatTok{0.8490}\NormalTok{, }\FloatTok{0.6972}\NormalTok{, }\FloatTok{0.2365}\NormalTok{, }\FloatTok{0.7036}\NormalTok{)}
\NormalTok{lambda }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{5.9347}\NormalTok{, }\FloatTok{4.1603}\NormalTok{, }\FloatTok{14.2532}\NormalTok{, }\FloatTok{6.1985}\NormalTok{, }\FloatTok{11.8649}\NormalTok{, }\FloatTok{2.4050}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Note that by running multiple simulation studies with varying numbers of sites and balanced visits, \texttt{ValidationExplorer} allows users to investigate all elements of the study design prior to data collection. In addition to specifying the numnber of sites and visits and parameter values, \texttt{simulate\_validatedData} requires that the user supply misclassification probabilities in the form of a matrix, subject to the constraint that rows in the matrix sum to one. An easy way to simulate a matrix of probabilities that meet these criteria is to leverage the \texttt{rdirch} function from the \texttt{nimble} package:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Simulate a hypothetical confusion matrix }
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{10092024}\NormalTok{) }
\NormalTok{Theta }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{apply}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\DecValTok{29}\NormalTok{, nspecies) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) \{nimble}\SpecialCharTok{::}\FunctionTok{rdirch}\NormalTok{(}\AttributeTok{alpha =}\NormalTok{ x)\}))}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Note that the above definition of \texttt{Theta} places high values on the diagonal of the matrix, corresponding to a high probability of correct classification. To lower the diagonal values, change the specification of \texttt{diag(29,\ nspecies)} to a smaller value. For example:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{another\_Theta }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{apply}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\DecValTok{5}\NormalTok{, nspecies) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{    nimble}\SpecialCharTok{::}\FunctionTok{rdirch}\NormalTok{(}\AttributeTok{alpha =}\NormalTok{ x)}
\NormalTok{  \}))}
\end{Highlighting}
\end{Shaded}

\linespread{1}

\texttt{another\_Theta} has lower values on the diagonal, and greater off-diagonal values (i.e., higher probability of misclassification). If you have specific values you would like to use for the assumed classification probabilities (e.g., from an experiment), these can be supplied manually:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{manual\_Theta }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FloatTok{0.9}\NormalTok{, }\FloatTok{0.05}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.02}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }
                       \FloatTok{0.01}\NormalTok{, }\FloatTok{0.7}\NormalTok{, }\FloatTok{0.21}\NormalTok{, }\FloatTok{0.05}\NormalTok{, }\FloatTok{0.02}\NormalTok{, }\FloatTok{0.01}\NormalTok{,  }
                       \FloatTok{0.01}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.95}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\FloatTok{0.01}\NormalTok{,}
                       \FloatTok{0.05}\NormalTok{, }\FloatTok{0.05}\NormalTok{, }\FloatTok{0.03}\NormalTok{, }\FloatTok{0.82}\NormalTok{, }\FloatTok{0.04}\NormalTok{, }\FloatTok{0.01}\NormalTok{,}
                       \FloatTok{0.01}\NormalTok{, }\FloatTok{0.015}\NormalTok{,  }\FloatTok{0.005}\NormalTok{,  }\FloatTok{0.005}\NormalTok{, }\FloatTok{0.95}\NormalTok{, }\FloatTok{0.015}\NormalTok{,}
                       \FloatTok{0.003}\NormalTok{, }\FloatTok{0.007}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\FloatTok{0.04}\NormalTok{, }\FloatTok{0.06}\NormalTok{, }\FloatTok{0.79}\NormalTok{), }
                       \AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{nrow =} \DecValTok{6}\NormalTok{)}

\FunctionTok{print}\NormalTok{(manual\_Theta)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       [,1]  [,2]  [,3]  [,4] [,5]  [,6]
## [1,] 0.900 0.050 0.010 0.010 0.02 0.010
## [2,] 0.010 0.700 0.210 0.050 0.02 0.010
## [3,] 0.010 0.010 0.950 0.010 0.01 0.010
## [4,] 0.050 0.050 0.030 0.820 0.04 0.010
## [5,] 0.010 0.015 0.005 0.005 0.95 0.015
## [6,] 0.003 0.007 0.100 0.040 0.06 0.790
\end{verbatim}

\linespread{1}

If you define the classifier manually, make sure the rows sum to 1 by running

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{all}\NormalTok{(}\FunctionTok{rowSums}\NormalTok{(manual\_Theta) }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\CommentTok{\# want this to return TRUE}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# If the above returns FALSE, see which one is not 1: }
\FunctionTok{rowSums}\NormalTok{(manual\_Theta)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 1 1 1 1 1
\end{verbatim}

\linespread{1}

With the required inputs defined, we can simulate data:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_data }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_validatedData}\NormalTok{(}
    \AttributeTok{n\_datasets =} \DecValTok{10}\NormalTok{, }\CommentTok{\# For demonstration {-}{-} use 50+ for real simulation studies}
    \AttributeTok{nsites =}\NormalTok{ nsites, }
    \AttributeTok{nvisits =}\NormalTok{ nvisits, }
    \AttributeTok{nspecies =}\NormalTok{ nspecies, }
    \AttributeTok{design\_type =} \StringTok{"FixedPercent"}\NormalTok{, }
    \AttributeTok{scenarios =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\FloatTok{0.15}\NormalTok{, }\FloatTok{0.3}\NormalTok{),}
    \AttributeTok{psi =}\NormalTok{ psi, }
    \AttributeTok{lambda =}\NormalTok{ lambda,}
    \AttributeTok{theta =}\NormalTok{ Theta, }
    \AttributeTok{save\_datasets =} \ConstantTok{FALSE}\NormalTok{, }\CommentTok{\# default value is FALSE}
    \AttributeTok{save\_masked\_datasets =} \ConstantTok{FALSE}\NormalTok{, }\CommentTok{\# default value is FALSE}
    \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"Fixed\_Effort"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Note that we specified the design type through the argument \texttt{design\_type\ =\ "FixedPercent"}, with the possible scenarios defined as the vector \texttt{scenarios\ =\ c(0.05,\ 0.1,\ 0.15,\ 0.3)}. These two arguments specify the set of alternative validation designs we will compare in our simulation study. Under the first validation design, 5\% of recordings from each visit to a site are validated, while in the second validation design 10\% of recordings from each visit to a site are validated, and so on.
Additionally, we have assumed that all selected recordings are successfully validated because we have not specified the \texttt{confirmable\_limits} argument, which is \texttt{NULL} by default. If we believed that the probability a randomly selected recording from detector-night \((i,j)\) lies between 0.4 and 0.6 (as in the main manuscript), for example, we would simulate data as follows:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_data\_with\_conf\_limits }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_validatedData}\NormalTok{(}
    \AttributeTok{n\_datasets =} \DecValTok{10}\NormalTok{,}
    \AttributeTok{nsites =}\NormalTok{ nsites, }
    \AttributeTok{nvisits =}\NormalTok{ nvisits, }
    \AttributeTok{nspecies =}\NormalTok{ nspecies, }
    \AttributeTok{design\_type =} \StringTok{"FixedPercent"}\NormalTok{, }
    \AttributeTok{scenarios =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.1}\NormalTok{, }\FloatTok{0.15}\NormalTok{, }\FloatTok{0.3}\NormalTok{),}
    \AttributeTok{psi =}\NormalTok{ psi, }
    \AttributeTok{lambda =}\NormalTok{ lambda,}
    \AttributeTok{theta =}\NormalTok{ Theta, }
    \AttributeTok{confirmable\_limits =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.4}\NormalTok{, }\FloatTok{0.6}\NormalTok{), }\CommentTok{\# specify the range for the confirmability}
    \AttributeTok{save\_datasets =} \ConstantTok{FALSE}\NormalTok{, }
    \AttributeTok{save\_masked\_datasets =} \ConstantTok{FALSE}\NormalTok{, }
    \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"Fixed\_Effort"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

This argument assumes the probability a call can be confirmed varies across site-visits, falling within the specified range; we can see this in the first 10 site-visits from the first dataset simulated under validation scenario 1:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# validation scenario 1, dataset 1}
\NormalTok{sim\_data\_with\_conf\_limits}\SpecialCharTok{$}\NormalTok{masked\_dfs[[}\DecValTok{1}\NormalTok{]][[}\DecValTok{1}\NormalTok{]] }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(site, visit) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{prop\_confirmable =} \FunctionTok{unique}\NormalTok{(prop\_confirmable)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{print}\NormalTok{(}\AttributeTok{n =} \DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has regrouped the output.
## i Summaries were computed grouped by site and visit.
## i Output is grouped by site.
## i Use `summarise(.groups = "drop_last")` to silence this message.
## i Use `summarise(.by = c(site, visit))` for per-operation grouping
##   (`?dplyr::dplyr_by`) instead.
\end{verbatim}

\begin{verbatim}
## # A tibble: 120 x 3
## # Groups:   site [30]
##     site visit prop_confirmable
##    <int> <int>            <dbl>
##  1     1     1            0.496
##  2     1     2            0.440
##  3     1     3            0.566
##  4     1     4            0.486
##  5     2     1            0.426
##  6     2     2            0.556
##  7     2     3            0.511
##  8     2     4            0.429
##  9     3     1            0.513
## 10     3     2            0.493
## # i 110 more rows
\end{verbatim}

\linespread{1}

We continue our demonstration using the \texttt{sim\_data} object, which assumes that all selected recordings can be confirmed.

To understand the output from \texttt{simulate\_validatedData}, we can investigate \texttt{sim\_data}. The output is a list, containing three objects:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(sim\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "full_datasets" "zeros"         "masked_dfs"
\end{verbatim}

\linespread{1}

We examine each of these objects below:

\begin{itemize}
\tightlist
\item
  \texttt{full\_datasets}: A list of length \texttt{n\_datasets} with unmasked datasets. These are the datasets under complete validation so that every recording has an autoID and a true species label. We opted to not save these datasets to the working directory by setting \texttt{save\_datasets\ =\ FALSE}. If we had specified \texttt{save\_datasets\ =\ TRUE}, then these will be saved individually in \texttt{directory} as \texttt{dataset\_n.rds}, where \texttt{n} is the dataset number. As an example of one element in \texttt{sim\_data\$full\_datasets}, we examine the third simulated full dataset:
\end{itemize}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{full\_dfs }\OtherTok{\textless{}{-}}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{full\_datasets}
\FunctionTok{head}\NormalTok{(full\_dfs[[}\DecValTok{3}\NormalTok{]]) }\CommentTok{\# Dataset number 3 if all recordings were validated}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 10
## # Groups:   site, visit [1]
##    site visit true_spp id_spp lambda   psi  theta     z count    Y.
##   <int> <int>    <int>  <int>  <dbl> <dbl>  <dbl> <int> <int> <int>
## 1     1     1        1      1   5.93 0.633 0.954      1     4    24
## 2     1     1        1      1   5.93 0.633 0.954      1     4    24
## 3     1     1        1      1   5.93 0.633 0.954      1     4    24
## 4     1     1        1      1   5.93 0.633 0.954      1     4    24
## 5     1     1        4      2   6.20 0.697 0.0289     1     1    24
## 6     1     1        3      3  14.3  0.849 0.826      1    10    24
\end{verbatim}

\linespread{1}

Notice that in addition to the site, visit, true species and autoID (\texttt{id\_spp}) columns, the parameter values (\texttt{lambda}, \texttt{psi}, and \texttt{theta}) are given for each true species-autoID combination. In addition, the occupancy state \texttt{z} for the true species is given and the \texttt{count} of calls at that site visit with a specific true species-autoID label combination. For example, at site 1, visit 1, there are four calls from species 1 that are assigned autoID 1, yielding 4 rows with \texttt{count\ =\ 4}. There is also one call from species 4 that was assigned a species 2 label with probability 0.02893559. Because this happened once, it is documented with \texttt{count\ =\ 1} and only occupies a single row. Next, we can see that there were 10 calls that were correctly identified as species 3; ten rows will have \texttt{true\_spp\ =\ 3} and \texttt{autoID\ =\ 3}. Finally, the \texttt{Y.} column tells us how many observations were made from all species at that site visit; for visit 1 to site 1, the unique value is 24. That is, the 25th row of this dataset will contain the first observation from visit 2 to site 1.

\begin{itemize}
\tightlist
\item
  \texttt{zeros}: A list of length \texttt{n\_datasets} containing the true species-autoID combinations that were never observed at each site visit. These zero counts are necessary for the model to identify occurrence probabilities and relative activity rates. The \texttt{count} column, which, again, contains the count of each site-visit-true\_spp-id\_spp combination, is zero for all entries. For example, in dataset 3 (below), species 2 was not present at site 1, so it could not be classified as species 1 (first row). Additionally, species 3 was present at site 1, but it was never classified as species 1 on visit 1 (second row). If \texttt{save\_datasets\ =\ TRUE}, the zeros for each dataset will also be saved in \texttt{directory} individually as \texttt{zeros\_in\_dataset\_n.rds}, where \texttt{n} is the dataset number.
\end{itemize}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{zeros }\OtherTok{\textless{}{-}}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros}

\CommentTok{\# The site{-}visit{-}true\_spp{-}autoID combinations that were never observed in}
\CommentTok{\# dataset 3. Notice that count = 0 for all rows! }
\FunctionTok{head}\NormalTok{(zeros[[}\DecValTok{3}\NormalTok{]]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 10
## # Groups:   site, visit [1]
##    site visit true_spp id_spp lambda   psi   theta     z count    Y.
##   <int> <int>    <int>  <int>  <dbl> <dbl>   <dbl> <int> <int> <int>
## 1     1     1        2      1   4.16 0.612 0.0286      0     0    24
## 2     1     1        3      1  14.3  0.849 0.0137      1     0    24
## 3     1     1        4      1   6.20 0.697 0.0426      1     0    24
## 4     1     1        5      1  11.9  0.236 0.00559     0     0    24
## 5     1     1        6      1   2.40 0.704 0.00312     1     0    24
## 6     1     1        1      2   5.93 0.633 0.0159      1     0    24
\end{verbatim}

\linespread{1}

\begin{itemize}
\tightlist
\item
  \texttt{masked\_dfs}: A nested list containing each dataset masked under each scenario. For example, \texttt{masked\_dfs{[}{[}4{]}{]}{[}{[}3{]}{]}} contains dataset 3, assuming that it was validated according to scenario 4 (30\% of recordings randomly sampled from each site-visit for validation). If \texttt{save\_masked\_datasets\ =\ TRUE}, then each dataset/scenario combination is saved individually in \texttt{directory} as \texttt{dataset\_n\_masked\_under\_scenario\_s.rds}, where \texttt{n} is the dataset number and \texttt{s} is the scenario number.
\end{itemize}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{masked\_dfs }\OtherTok{\textless{}{-}}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs}

\CommentTok{\# View dataset 3 subjected to the validation design in scenario 4: }
\CommentTok{\# randomly select and validate 30\% of recordings from the first visit }
\CommentTok{\# to each site }
\FunctionTok{head}\NormalTok{(masked\_dfs[[}\DecValTok{4}\NormalTok{]][[}\DecValTok{3}\NormalTok{]], }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 13
##     site visit true_spp id_spp lambda   psi  theta     z count    Y. selected
##    <int> <int>    <int>  <int>  <dbl> <dbl>  <dbl> <int> <int> <int>    <dbl>
##  1     1     1       NA      1   5.93 0.633 0.954      1     4    24        0
##  2     1     1       NA      1   5.93 0.633 0.954      1     4    24        0
##  3     1     1       NA      1   5.93 0.633 0.954      1     4    24        0
##  4     1     1       NA      1   5.93 0.633 0.954      1     4    24        0
##  5     1     1       NA      2   6.20 0.697 0.0289     1     1    24        0
##  6     1     1        3      3  14.3  0.849 0.826      1    10    24        1
##  7     1     1        3      3  14.3  0.849 0.826      1    10    24        1
##  8     1     1        3      3  14.3  0.849 0.826      1    10    24        1
##  9     1     1       NA      3  14.3  0.849 0.826      1    10    24        0
## 10     1     1        3      3  14.3  0.849 0.826      1    10    24        1
## # i 2 more variables: unique_call_id <chr>, scenario <int>
\end{verbatim}

\linespread{1}

The name of this nested list comes from the way that validation effort is simulated: recordings that are not selected for validation have their \texttt{true\_spp} label masked with an \texttt{NA}. Notice that in the example output, all entries in the dataset are identical to the unmasked version output in \texttt{full\_dfs} above, with the exception of the \texttt{true\_spp} column. From this column we can see that calls 1-5 and 9 were not selected for validation (because \texttt{true\_spp\ =\ NA}), while recordings 6-8 and 10 were (because the true species label is not marked as \texttt{NA}).

\subsubsection{\texorpdfstring{Summarize validation effort \label{summarizeEffort}}{Summarize validation effort }}\label{summarize-validation-effort}

For most simulations, it will be useful to summarize the number of recordings that are validated under a given validation design and scenario. This can be accomplished using the \texttt{summarize\_n\_validated} function:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summarize\_n\_validated}\NormalTok{(}
  \AttributeTok{data\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs, }
  \AttributeTok{theta\_scenario =} \StringTok{"1"}\NormalTok{, }
  \AttributeTok{scenario\_numbers =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 4
##   theta_scenario scenario n_selected n_validated
##   <chr>          <chr>         <dbl>       <dbl>
## 1 1              1              218.        218.
## 2 1              2              375.        375.
## 3 1              3              540.        540.
## 4 1              4             1021.       1021.
\end{verbatim}

\linespread{1}

We can see here that any of the validation designs considered in our simulations will remain well within budget.

\subsection{\texorpdfstring{Step 3: MCMC tuning \label{tune}}{Step 3: MCMC tuning }}\label{step-3-mcmc-tuning}

Running a complete simulation study can be time consuming. In an effort to help users improve the efficiency of their simulations, we provide the \texttt{tune\_mcmc} function, which outputs information about possible values for the warmup and total number of iterations required for the MCMC to reach approximate convergence. This function takes in a masked dataset and the corresponding zeros, fits a model to these data, and outputs an estimated run time for 10,000 iterations, as well as the estimated number of required warmup and total iterations. These are intended to assist tuning of the MCMC algorithm, which is done by the user in the following steps, which we walk through in greater detail below:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Use \texttt{tune\_mcmc} to fit a model with multiple long chains.
\item
  Create trace plots for all model parameters.
\item
  Examine effective sample sizes \(n_\text{eff}\) and Gelman-Rubin statistics \(\hat{R}\) for all parameters.
\item
  Choose values for the number of iterations and warmup that are slightly larger than what is needed based on steps 1-3. This may help ensure that a greater number of model fits are available to inform simulation study results.
\end{enumerate}

\subsubsection{Fit a model}\label{fit-a-model}

As in the main text, we use a dataset from the scenario with the lowest number of validated recordings, as we expect the greatest number of iterations for this scenario. In our example, this is scenario 1 , in which an average of \(\approx 218\) recordings are validated per dataset (Section \ref{summarizeEffort}).

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scenario\_number }\OtherTok{\textless{}{-}} \DecValTok{1}
\NormalTok{dataset\_number }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(masked\_dfs[[scenario\_number]]), }\DecValTok{1}\NormalTok{)}

\NormalTok{tune\_list }\OtherTok{\textless{}{-}} \FunctionTok{tune\_mcmc}\NormalTok{(}
  \AttributeTok{dataset =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs[[scenario\_number]][[dataset\_number]], }
  \AttributeTok{zeros =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros[[dataset\_number]] }
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Fitting MCMC in parallel ... this may take a few minutes"
\end{verbatim}

\linespread{1}

The output from \texttt{tune\_mcmc} is a list containing draws from the fitted model, the time required to fit the model with 10,000 draws, MCMC diagnostics and guesses for the number of iterations and warmup required to reliably fit a model. If the guessed values for total iterations and/or warmup are greater than 10,000 draws, an error is issued. We can see the names for each object by running the following block:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(tune\_list)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "max_iter_time"    "min_warmup"       "min_iter"         "fit"             
## [5] "MCMC_diagnostics"
\end{verbatim}

\linespread{1}

The first element is the time required to fit a model with three chains of 10,000 iterations each:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{max\_iter\_time}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Time difference of 4.698816 mins
\end{verbatim}

\linespread{1}

This may seem insignificant, but over the course of an entire simulations study with 5 scenarios \(\times\) 50 datasets, that corresponds to around 8 hours of run time. Using fewer than 10,000 iterations will substantially reduce the time to run a simulation study.

\subsubsection{Create trace plots}\label{create-trace-plots}

To decide the number of iterations and warmup for use in a simulation study, we recommend beginning by creating trace plots, which show how the sampled values of a parameter evolve over the course of each Markov chain. To ensure the MCMC algorithm will characterize the posterior distribution well, we need to check that chains are stationary and mixing well, and that effective sample sizes are sufficiently large to characterize the posterior. Trace plots are especially useful for assessing the first of these. To create a trace plot using the bayesplot package (Gabry et al. 2019) for a single parameter, run the following:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load bayesplot package specifically designed for visualizing }
\FunctionTok{library}\NormalTok{(bayesplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## This is bayesplot version 1.13.0
\end{verbatim}

\begin{verbatim}
## - Online documentation and vignettes at mc-stan.org/bayesplot
\end{verbatim}

\begin{verbatim}
## - bayesplot theme set to bayesplot::theme_default()
\end{verbatim}

\begin{verbatim}
##    * Does _not_ affect other ggplot2 plots
\end{verbatim}

\begin{verbatim}
##    * See ?bayesplot_theme_set for details on theme setting
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# extract the fitted model from tune\_mcmc output}
\NormalTok{fit }\OtherTok{\textless{}{-}}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{fit}

\CommentTok{\# create traceplot}
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{pars =} \StringTok{"lambda[5]"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{usingValidationExplorer_files/figure-latex/unnamed-chunk-6-1.pdf}}

\linespread{1}

We can see that far fewer than 10,000 iterations are likely required because the chains are mixing well after a few hundred iterations. This is shown by strongly overlapping chains, with no one chain appearing by itself in a region of the parameter space. Chains also appear to be stationary because they do not wander vertically substantially after the first few hundred iterations.

We need to check that chains are stationary and mixing for all parameters. One way to accelerate visual inspection this is through the \texttt{regex\_pars} argument, which shows relative activity parameters for all species as in the following three code blocks.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{usingValidationExplorer_files/figure-latex/unnamed-chunk-7-1.pdf}}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"psi"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{usingValidationExplorer_files/figure-latex/unnamed-chunk-8-1.pdf}}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create a traceplot for all elements of the confusion matrix}
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"theta"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{usingValidationExplorer_files/figure-latex/unnamed-chunk-9-1.pdf}}

\linespread{1}

In all of the trace plots for all of the parameters, chains appear to mix quickly, meaning that it is possible a far smaller number of iterations may be suitable for a simulation study. A good place to start for reducing the number of iterations is from the output given by \texttt{tune\_mcmc}. In our case, we can see that a guess for the minimum number of iterations is 1500 with a warmup of 500:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1500
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 500
\end{verbatim}

\linespread{1}

It is possible to use these values to zoom in on the trace plots by using the \texttt{window} argument:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{, }\AttributeTok{window =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{usingValidationExplorer_files/figure-latex/unnamed-chunk-11-1.pdf}}

\linespread{1}

Once again, we see the three chains overlap strongly after around 500 iterations and sample around a horizontal line.

After making traceplots and zooming in for all parameters (not all plots are shown here), it appears that the guessed warmup value of 500 output from \texttt{tune\_mcmc} is a reasonable choice. Even so, we increase our iterations and warmup beyond these minimum values in Section \ref{runSims} to avoid simulations failing due to convergence.

\subsubsection{Examine effective sample size and Gelman-Rubin statistics}\label{examine-effective-sample-size-and-gelman-rubin-statistics}

As a final step, we examine the effective sample sizes (out of 10,000 draws) and \(\hat{R}\) values. The effective sample size statistics \texttt{ess\_bulk} and \texttt{ess\_tail} are MCMC diagnostic statistics that summarizes the number of effectively independent draws from a parameter's posterior distribution the Markov chain contains. If a parameter has a large value in the \texttt{ess\_bulk} column, then it is likely that inference based on sampled draws will characterize the center of the posterior distribution well. The \texttt{ess\_tail} column, on the other hand, describes how much information is available about posterior tail probabilities. Once again, we want a large value for \texttt{ess\_tail}, preferably \texttt{ess\_tail}\(\geq 250\).

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{MCMC\_diagnostics}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      parameter   ess_bulk   ess_tail      Rhat
## 1    lambda[1]  4010.3844  5478.6189 1.0014322
## 2    lambda[2]  4541.3128  6150.1755 1.0004919
## 3    lambda[3]  2941.5781  4363.2113 1.0011009
## 4    lambda[4]  2711.4849  4254.0632 1.0002127
## 5    lambda[5]  2570.1947  4213.2635 1.0010610
## 6    lambda[6]  4020.5515  5643.9438 1.0005186
## 7       psi[1] 28997.5595 29555.0070 0.9999849
## 8       psi[2] 29609.0616 29330.2877 1.0000206
## 9       psi[3] 29760.3748 27887.6184 1.0000555
## 10      psi[4] 23975.0248 27377.9747 1.0000715
## 11      psi[5] 24430.0635 16779.9825 0.9999801
## 12      psi[6] 10539.0104 19087.2826 1.0000980
## 13 theta[1, 1]  1510.9436  2981.0414 1.0029574
## 14 theta[2, 1]  4245.2615  5663.1406 1.0003426
## 15 theta[3, 1]  1532.6217  2286.1564 1.0013924
## 16 theta[4, 1]   706.0675   362.9901 1.0044155
## 17 theta[5, 1]  1477.7736  2552.1892 1.0022036
## 18 theta[6, 1]  2955.3356  3514.0073 1.0006620
## 19 theta[1, 2]  2482.4887  3020.6973 1.0002891
## 20 theta[2, 2]  4603.6793  7381.3186 1.0005044
## 21 theta[3, 2]  2798.7675  3834.4404 1.0011781
## 22 theta[4, 2]  2506.2863  2808.7971 1.0013255
## 23 theta[5, 2]  5283.6460  5322.1910 1.0009170
## 24 theta[6, 2]  3324.9653  3163.5956 1.0006352
## 25 theta[1, 3]   669.1196   342.4874 1.0052628
## 26 theta[2, 3]  1602.4319  2924.1140 1.0007939
## 27 theta[3, 3]  3540.4928  5994.4546 1.0006117
## 28 theta[4, 3]  1635.8310  2333.6818 1.0006387
## 29 theta[5, 3]  1509.7602   936.3281 1.0018524
## 30 theta[6, 3]  1157.0937  2111.9690 1.0019403
## 31 theta[1, 4]  3036.2638  4640.3312 1.0014318
## 32 theta[2, 4]  3843.5858  3831.4358 1.0006416
## 33 theta[3, 4]  3158.3387  5720.7725 1.0019079
## 34 theta[4, 4]  2131.3114  4571.8066 1.0005209
## 35 theta[5, 4]  2492.3802  3922.6714 1.0006321
## 36 theta[6, 4]  5510.1416  5519.6696 1.0000828
## 37 theta[1, 5]  5067.4315  6497.4803 1.0002322
## 38 theta[2, 5]  2703.0205  3518.8482 1.0016831
## 39 theta[3, 5]  3158.3929  3484.4760 1.0004970
## 40 theta[4, 5]  5446.6643  8411.0873 1.0002630
## 41 theta[5, 5]  2674.8345  5611.3777 1.0002954
## 42 theta[6, 5]  4726.8597  5000.5934 1.0013355
## 43 theta[1, 6]  3066.7256  3253.1427 1.0013833
## 44 theta[2, 6]  3846.8655  3683.5377 1.0018186
## 45 theta[3, 6]  3386.7769  3922.0851 1.0008767
## 46 theta[4, 6]  3983.6635  4897.7234 1.0011820
## 47 theta[5, 6]  3455.5466  4330.8743 1.0005549
## 48 theta[6, 6]  3594.9695  7309.1236 1.0005972
\end{verbatim}

\linespread{1}

For all parameters, the bulk and tail effective sample sizes are fairly large, meaning that even with fewer than 10,000 draws, we could expect \(n_\text{eff} \geq 250,\) allowing us to characterize both the center and tails of the posteriors for all parameters with these draws. Furthermore, the \(\hat{R}\) values for all parameters is near 1. In general, we want values of \(\hat{R} \leq 1.1\) for chains to be considered converged. We can double check by recomputing these statistics on shortened chains:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# for each chain, extract iterations 1001:2500 for all parameters}
\NormalTok{shortened }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(fit, }\ControlFlowTok{function}\NormalTok{(x) x[}\DecValTok{1001}\SpecialCharTok{:}\DecValTok{2500}\NormalTok{,])}

\CommentTok{\# summarize the shortened chains and select the effective sample }
\CommentTok{\# size columns. mcmc\_sum is an internal function used inside of \textasciigrave{}run\_sims\textasciigrave{}, but}
\CommentTok{\# we use it here to quickly obtain MCMC diagnostics for each parameter}
\FunctionTok{mcmc\_sum}\NormalTok{(shortened, }\AttributeTok{truth =} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(shortened[[}\DecValTok{1}\NormalTok{]]))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(parameter, ess\_bulk, ess\_tail, Rhat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      parameter  ess_bulk  ess_tail      Rhat
## 1    lambda[1]  554.6431 1033.4194 1.0099487
## 2    lambda[2]  675.2947  967.6004 1.0140986
## 3    lambda[3]  554.9902 1033.3352 1.0040760
## 4    lambda[4]  474.3933  848.3479 1.0042330
## 5    lambda[5]  477.6492  950.0395 1.0053510
## 6    lambda[6]  514.7060  722.7508 1.0079439
## 7       psi[1] 4466.8190 4057.4672 1.0000851
## 8       psi[2] 4522.0097 4283.5827 1.0001923
## 9       psi[3] 4423.5174 4154.7669 1.0010205
## 10      psi[4] 3476.0965 4212.6367 0.9999102
## 11      psi[5] 4365.5975 4123.4720 1.0003974
## 12      psi[6] 1634.0284 3340.4332 1.0002776
## 13 theta[1, 1]  233.7635  651.0055 1.0136188
## 14 theta[2, 1]  597.6874  727.2412 1.0159901
## 15 theta[3, 1]  416.7783  471.4902 1.0114489
## 16 theta[4, 1]  373.8558  373.6366 1.0119230
## 17 theta[5, 1]  318.3571  553.3239 1.0062527
## 18 theta[6, 1]  586.2165  537.8601 1.0016866
## 19 theta[1, 2]  443.6049  555.6283 1.0044771
## 20 theta[2, 2]  581.4572  985.7036 1.0163135
## 21 theta[3, 2]  367.9560  542.4209 1.0095890
## 22 theta[4, 2]  388.8405  609.8069 1.0048772
## 23 theta[5, 2]  724.3042  725.5558 1.0034936
## 24 theta[6, 2]  515.1060  425.0285 1.0034494
## 25 theta[1, 3]  138.0932  148.5343 1.0222518
## 26 theta[2, 3]  247.9299  494.1075 1.0173245
## 27 theta[3, 3]  601.4032 1201.8622 1.0016004
## 28 theta[4, 3]  281.2416  543.6097 1.0048992
## 29 theta[5, 3]  279.0991  339.0779 1.0067994
## 30 theta[6, 3]  180.4327  409.5847 1.0148556
## 31 theta[1, 4]  598.9422  780.9283 1.0095303
## 32 theta[2, 4]  570.8692  439.4489 1.0029617
## 33 theta[3, 4]  473.4890 1191.1858 1.0038196
## 34 theta[4, 4]  608.0050 1221.2084 1.0081656
## 35 theta[5, 4]  446.7676  800.3200 1.0019387
## 36 theta[6, 4]  741.0322 1025.1841 1.0064648
## 37 theta[1, 5]  977.6644 1104.4073 1.0026449
## 38 theta[2, 5]  380.9374  546.1040 1.0070073
## 39 theta[3, 5]  548.6054  670.3795 1.0061442
## 40 theta[4, 5]  722.6617 1122.3326 1.0044668
## 41 theta[5, 5]  493.6208  885.6230 1.0050890
## 42 theta[6, 5]  698.6240  716.3629 1.0040273
## 43 theta[1, 6]  572.8004  572.5859 1.0047225
## 44 theta[2, 6]  619.2738  571.6925 1.0058776
## 45 theta[3, 6]  541.7884  755.6583 1.0031853
## 46 theta[4, 6]  759.2779 1104.3320 1.0072576
## 47 theta[5, 6]  423.1944  418.0043 1.0068129
## 48 theta[6, 6]  626.0581 1275.8271 1.0052231
\end{verbatim}

\linespread{1}

These results appear satisfactory, with effective sample sizes in both the tail and bulk of the posterior distributions of more than 250 and \(\hat{R}\) near 1. Based on the results of MCMC tuning, it appears that using an MCMC with at least 1500 iterations with at least 500 discarded as warmup should to produce good results for our simulation study.

\subsubsection{Set iterations for simulation}\label{set-iterations-for-simulation}

Based on our findings in the MCMC tuning step, we set the number of iterations for simulation to be slightly higher to guard against convergence issues that preclude using a fitted model for inference:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# to be used in the following section }
\NormalTok{iters\_for\_sims }\OtherTok{\textless{}{-}}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{1000}
\NormalTok{warmup\_for\_sims }\OtherTok{\textless{}{-}}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup }\SpecialCharTok{+} \DecValTok{500}
\end{Highlighting}
\end{Shaded}

\linespread{1}

\subsubsection{A note about non-convergence while tuning}\label{a-note-about-non-convergence-while-tuning}

In some instances, we have run \texttt{tune\_mcmc} with a dataset and received a series of error messages that convergence was not reached in under 10,000 iterations. If this persists after trying to fit several other datasets, we have several options:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  We could increase the number of iterations in the simulation study to be above 10,000 -- perhaps to 20,000 and settle for a longer run time of the simulation study.
\item
  We could take this as a sign that the level of effort is insufficient to identify model parameters. In this case, this scenario should not be considered.
\end{enumerate}

In our experience fitting these models, the second option seems to often be the case, and we encourage users to remove scenarios from consideration if models fit during the tuning step do not reach convergence within 10,000 iterations. It is possible that all validation scenarios -- including ones with very large levels of validation effort -- will lead to a lack of convergence if the number of sites and visits are very low, in which case the number of sites and visits should be re-evaluated.

We emphasize that the results from \texttt{tune\_mcmc} are from a single model fit; they are supplied only as guidelines, and we encourage users to increase the number of iterations above the minimum values output from \texttt{tune\_mcmc}. While each model fit will take slightly longer with an increased number of total iterations, this approach may save time in the long run by avoiding the need to re-run simulations.

\subsection{\texorpdfstring{Step 4: Fit models to simulated data \label{runSims}}{Step 4: Fit models to simulated data }}\label{step-4-fit-models-to-simulated-data}

With the simulated dataset and some informed choices about tuning of the MCMC, we use \texttt{run\_sims} to run the simulations:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sims\_output }\OtherTok{\textless{}{-}} \FunctionTok{run\_sims}\NormalTok{(}
         \AttributeTok{data\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs, }
         \AttributeTok{zeros\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros, }
         \AttributeTok{DGVs =} \FunctionTok{list}\NormalTok{(}\AttributeTok{lambda =}\NormalTok{ lambda, }\AttributeTok{psi =}\NormalTok{ psi, }\AttributeTok{theta =}\NormalTok{ Theta), }
         \AttributeTok{theta\_scenario\_id =} \StringTok{"FE"}\NormalTok{, }\CommentTok{\# for "fixed effort"}
         \AttributeTok{parallel =} \ConstantTok{TRUE}\NormalTok{, }
         \AttributeTok{niter =}\NormalTok{ iters\_for\_sims, }
         \AttributeTok{nburn =}\NormalTok{ warmup\_for\_sims,  }
         \AttributeTok{thin =} \DecValTok{1}\NormalTok{,}
         \AttributeTok{save\_fits =} \ConstantTok{TRUE}\NormalTok{, }
         \AttributeTok{save\_individual\_summaries\_list =} \ConstantTok{FALSE}\NormalTok{, }
         \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"Fixed\_Effort"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Beginning scenario 1.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 12:02:39.546497
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 2.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 12:23:08.265121
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 3.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 12:50:55.966194
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 4.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 13:28:53.023613
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\linespread{1}

The output object, \texttt{sims\_output} is a dataframe with summaries of the MCMC draws for each parameter estimated from each dataset under each validation scenario. Summaries include the posterior mean, standard deviation, Naive standard error, Time-series standard error, quantiles for 50\% and 95\% posterior intervals, median, and MCMC diagnostics (Gelman-Rubin statistic, and effective samples sizes in the tails and bulk of the distribution).

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(sims\_output)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1920 obs. of  19 variables:
##  $ parameter     : chr  "lambda[1]" "lambda[2]" "lambda[3]" "lambda[4]" ...
##  $ Mean          : num  6.05 4.81 14.08 5.98 11.71 ...
##  $ SD            : num  0.358 0.336 0.469 0.493 0.795 ...
##  $ Naive SE      : num  0.00534 0.00501 0.00699 0.00734 0.01184 ...
##  $ Time-series SE: num  0.0128 0.0144 0.0186 0.0262 0.0282 ...
##  $ 2.5%          : num  5.38 4.17 13.18 5.04 10.23 ...
##  $ 25%           : num  5.81 4.57 13.75 5.66 11.19 ...
##  $ 50%           : num  6.04 4.8 14.07 5.96 11.66 ...
##  $ 75%           : num  6.29 5.04 14.41 6.29 12.23 ...
##  $ 97.5%         : num  6.75 5.47 14.97 7.01 13.33 ...
##  $ Rhat          : num  1 1.01 1.01 1.01 1 ...
##  $ ess_bulk      : num  660 535 622 330 778 ...
##  $ ess_tail      : num  975 832 891 408 757 ...
##  $ truth         : num  5.93 4.16 14.25 6.2 11.86 ...
##  $ capture       : num  1 0 1 1 1 1 1 1 1 1 ...
##  $ converge      : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ theta_scenario: chr  "FE" "FE" "FE" "FE" ...
##  $ scenario      : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ dataset       : int  1 1 1 1 1 1 1 1 1 1 ...
\end{verbatim}

\linespread{1}

Note that we fit all models in parallel to reduce simulation time; we encourage users to do the same. However, if you fit models with \texttt{parallel\ =\ FALSE} in \texttt{run\_sims}, the console will display the messages NIMBLE prints as it compiles code for each model. Internally, we specify a custom distribution to compute the marginal probabilities for ambiguous autoID labels, and you will see a warning about overwriting a custom user-specified distribution if \texttt{parallel\ =\ FALSE}. These warnings can be safely ignored.

\subsection{\texorpdfstring{Step 5: Visualize simulations \label{viz}}{Step 5: Visualize simulations }}\label{step-5-visualize-simulations}

Once models have been fit to all simulated datasets, you can visualize results using several functions. We recommend beginning with the most detailed functions, which are \texttt{visualize\_parameter\_group} and \texttt{visualize\_single\_parameter}. The plots output from these functions show many following features of the simulation study. These are

\begin{itemize}
\tightlist
\item
  Facet grids: parameters (only for \texttt{visualize\_parameter\_group})
\item
  X-axis: Manual verification scenario
\item
  y-axis: parameter values
\item
  Small grey error bars: 95\% posterior interval for an individual model fit where all parameters were below \texttt{convergence\_threshold}.
\item
  Colored error bars: average 95\% posterior interval across all converged models under that scenario.
\item
  Color: Coverage, or the rate at which 95\% posterior intervals contain the true data-generating parameter value.
\item
  Black points: the true value of the parameter
\item
  Red points: average posterior mean
\end{itemize}

The \texttt{visualize\_parameter\_group} function is useful for examining an entire set of parameters, such as all relative activity parameters. For example, we can visualize the inference for the relative activity parameters in the first three scenarios in our simulation study above by running the code below.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_output, }
  \AttributeTok{pars =} \StringTok{"lambda"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{,}
  \AttributeTok{convergence\_threshold =} \FloatTok{1.05}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:vizGroup} Example output from the visualize\_parameter\_group function. Results are faceted by parameter, with the x-axis indicating the validation scenario number, and the y-axis showing the data generating value (black point). Red points show average posterior means, small grey intervals show 95\% posterior intervals from converged model fits and colored intervals are average 95\% posterior intervals. Coverage is shown by color, with blue corresponding to low coverage.}]{usingValidationExplorer_files/figure-latex/vizGroup-1.pdf}}
\caption{\label{fig:vizGroup} Example output from the \texttt{visualize\_parameter\_group} function. Results are faceted by parameter, with the x-axis indicating the validation scenario number, and the y-axis showing the data generating value (black point). Red points show average posterior means, small grey intervals show 95\% posterior intervals from converged model fits and colored intervals are average 95\% posterior intervals. Coverage is shown by color, with blue corresponding to low coverage.}
\end{figure}

\linespread{1}

The output shown in Figure \ref{fig:vizGroup} indicates that under all validation scenarios we considered, the expected inference for relative activity rates of species 1-4 and 6 meets our measurable objectives: the posterior interval width is less than three for these species and there is minimal estimation error. However, note that under validation scenario 1 and 2, fewer of the models converged within 2500 iterations of the MCMC, which is visible from smaller number of grey intervals. This suggests that a higher level of validation effort could be beneficial. Additionally, average interval width is never below 3 for species 5; none of the designs considered here meet the measurable objective for this species. We can see this more clearly by examining output through alternative visualization functions.

A first step would be to use \texttt{visualize\_single\_parameter}, which takes the same arguments as the previous visualization function:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_single\_parameter}\NormalTok{(}
\NormalTok{  sims\_output, }\AttributeTok{par =} \StringTok{"lambda[5]"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{, }
  \AttributeTok{convergence\_threshold =} \FloatTok{1.05}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:vizOne}Example output from visualize\_single\_parameter is similar to that of visualize\_parameter\_group: the x-axis shows the validation scenario, and the y-axis shows the true value of the parameter (black point). Average posterior means are shown by red points, individual 95\% posterior intervals from converged model fits are shown as small grey error bars and average 95\% posterior intervals are shown by the larger colored error bars. The coverage is indicated by color.}]{usingValidationExplorer_files/figure-latex/vizOne-1.pdf}}
\caption{\label{fig:vizOne}Example output from \texttt{visualize\_single\_parameter} is similar to that of \texttt{visualize\_parameter\_group}: the x-axis shows the validation scenario, and the y-axis shows the true value of the parameter (black point). Average posterior means are shown by red points, individual 95\% posterior intervals from converged model fits are shown as small grey error bars and average 95\% posterior intervals are shown by the larger colored error bars. The coverage is indicated by color.}
\end{figure}

\linespread{1}

The greater detail of \texttt{visualize\_single\_parameter} in Figure \ref{fig:vizOne} underscores the difference in the number of converged models, shown by the number grey 95\% posterior interval for each converged model fit. The visualization also helps clarify that while average interval width is near 3 in scenario 2, it is still acceptable for our measurable objectives. Coverage for most relative activity parameters is also near-nominal under this validation scenario, which requires that around 375 recordings be validated in an average dataset. This can also be seen using the \texttt{plot\_width\_vs\_calls} function (Figure \ref{fig:plotWidth}), which compares average interval widths (and the IQR for interval widths) across scenarios based on the number of recordings validated. An example is provided below:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# obtain summary of validation effort as an object that can be used with }
\CommentTok{\# the summary plot functions plot\_x\_vs\_calls}
\NormalTok{s }\OtherTok{\textless{}{-}}  \FunctionTok{summarize\_n\_validated}\NormalTok{(}
  \AttributeTok{data\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs, }
  \AttributeTok{theta\_scenario =} \StringTok{"FE"}\NormalTok{, }\CommentTok{\# must not be NULL for the plot\_X\_vs\_calls functions}
  \AttributeTok{scenario\_numbers =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_width\_vs\_calls}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_output, }
  \AttributeTok{calls\_summary =}\NormalTok{ s, }
  \AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \StringTok{"FE"}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{2}\SpecialCharTok{:}\DecValTok{5}
\NormalTok{) }\SpecialCharTok{+} \CommentTok{\# add horizontal line at target 95\% CI width }
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{3}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dotted"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:plotWidth}Example output from plot\_width\_vs\_calls. The x-axis shows the number of validated recordings. Note that the level of effort increases with scenario number for the fixed-effort designs; this may not always be the case, for example, with a stratified-by-species design as in the main text. The y-axis shows the value of the average 95\% posterior interval width (point). The middle 50\% of interval widths for each parameter are shown by the error bars. Color indicates the parameter.}]{usingValidationExplorer_files/figure-latex/plotWidth-1.pdf}}
\caption{\label{fig:plotWidth}Example output from \texttt{plot\_width\_vs\_calls}. The x-axis shows the number of validated recordings. Note that the level of effort increases with scenario number for the fixed-effort designs; this may not always be the case, for example, with a stratified-by-species design as in the main text. The y-axis shows the value of the average 95\% posterior interval width (point). The middle 50\% of interval widths for each parameter are shown by the error bars. Color indicates the parameter.}
\end{figure}

\linespread{1}

We provide analogous functions \texttt{plot\_coverage\_vs\_calls} and \texttt{plot\_bias\_vs\_calls} taking identical arguments that show how coverage and estimation error change with the number of calls validated. Note that in all of our visualization functions, if no fitted models have \(\hat{R} \leq c\) for all parameters, where \(c\) is the specified convergence threshold under a given scenario, then the scenario will not appear on the x-axis. In our example, we used \(c = 1.1\).

To ensure that there aren't substantial problems with estimation of other model parameters, we can create plots for \(\psi\) and \(\Theta\):

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_output, }
  \AttributeTok{pars =} \StringTok{"psi"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{,}
  \AttributeTok{convergence\_threshold =} \FloatTok{1.05}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:vizPsi}We encourage users to check inference for other model parameters, even if they are not explicitly of interest based on measurable objectives. Here, we examine \textbackslash boldsymbol\{\textbackslash psi\}. Note that coverage for several parameters is slightly low. For the purpose of exposition, we only fit 10 datasets and we expect that coverage would be near nominal levels if 50 or more datasets were used in simulation.}]{usingValidationExplorer_files/figure-latex/vizPsi-1.pdf}}
\caption{\label{fig:vizPsi}We encourage users to check inference for other model parameters, even if they are not explicitly of interest based on measurable objectives. Here, we examine \(\boldsymbol{\psi}\). Note that coverage for several parameters is slightly low. For the purpose of exposition, we only fit 10 datasets and we expect that coverage would be near nominal levels if 50 or more datasets were used in simulation.}
\end{figure}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_output, }
  \AttributeTok{pars =} \StringTok{"theta"}\NormalTok{, }
  \AttributeTok{theta\_scenario =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{,}
  \AttributeTok{convergence\_threshold =} \FloatTok{1.05}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:plotTheta}Checking inference for the elements of the classification matrix \textbackslash Theta. For most parameters (facets), validation scenario 2 appears to lead to minimal estimation error and near-nominal coverage.}]{usingValidationExplorer_files/figure-latex/plotTheta-1.pdf}}
\caption{\label{fig:plotTheta}Checking inference for the elements of the classification matrix \(\Theta\). For most parameters (facets), validation scenario 2 appears to lead to minimal estimation error and near-nominal coverage.}
\end{figure}

\linespread{1}

The simulation results shown in Figure \ref{fig:vizPsi} and \ref{fig:plotTheta} don't immediately cause concern that inference for relative activity rates will be severely compromised for any of these validation designs. Some parameters have slightly low coverage, but we believe this is mostly due to the small number of datasets used in this example; users should increase the number of datasets to at least 50, which we expect would lead to coverage near nominal levels.

\subsection{\texorpdfstring{Take-aways from the Fixed-Effort Simulations \label{takeaway-FE}}{Take-aways from the Fixed-Effort Simulations }}\label{take-aways-from-the-fixed-effort-simulations}

Based on Figures \ref{fig:vizGroup} - \ref{fig:plotWidth}, we can rule out validation scenario 1, because the expected width of 95\% posterior intervals is greater than the threshold value of 3. Because of this, we might choose validation scenario 2 as one possible fixed effort validation design. This fixed effort design assumes that 10\% of recordings from each site-night are randomly selected for validation, leading to around 375 recordings being validated per dataset. In our simulations, posterior means for each \(\lambda_k\) appear to be nearly unbiased, with near-nominal coverage and average posterior interval widths less than or equal to 3 for this scenario. However, it is possible that for a given dataset, the interval width for \(\lambda_5\) will be larger than 3, regardless of the number of validated calls; error bars in Figure \ref{fig:plotWidth} overlap or exceed the dotted line in all scenarios.

In situations such as this one, a decision is required of the user. If a slightly larger interval width is acceptable, validating 10\% percent of recordings from all site-visits is reasonable. If it is not, then the LOVE will need to be increased beyond that in scenario 4 (1021 recordings). The question is whether potentially tripling the number of validated recordings will be worth the benefit of ensuring the relative activity level for species 5 is less than 3. This is a question about measurable objectives that we leave to the practitioner and their study priorities.

\newpage

\section{\texorpdfstring{Stratified-by-species example \label{stratEx}}{Stratified-by-species example }}\label{stratified-by-species-example}

In this section, we provide further details of the example in the main manuscript, which assumed a stratified-by-species design. In a stratified-by-species design, the random mechanism is a stratified random sample, with strata formed by the species labels assigned during automated classification (i.e., by autoID). In this type of design, the LOVE is the proportion of recordings selected to be validated for each species label.

We repeat the simulation study conducted in the main text in this section, providing greater detail for some of the steps. We assume the same measurable objectives as in Section \ref{FEEx}, but we now assume the maximum number of recordings that can be viewed by experts during the validation process is 1000.

\subsection{\texorpdfstring{Simulate data \label{simBySpp}}{Simulate data }}\label{simulate-data}

Using the same values for \texttt{psi}, \texttt{lambda} and \texttt{Theta} as in Section \ref{dataSimulation}, we simulate data using \texttt{simulate\_validatedData} with \texttt{design\_type\ =\ "BySpecies"} and set the probability of successfully validating a selected recording using the \texttt{confirmable\_limits} argument. This will yield simulated data in the format described in Section \ref{dataSimulation}.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_data }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_validatedData}\NormalTok{(}
  \AttributeTok{n\_datasets =} \DecValTok{10}\NormalTok{, }
  \AttributeTok{design\_type =} \StringTok{"BySpecies"}\NormalTok{,}
  \AttributeTok{scenarios =} \FunctionTok{list}\NormalTok{(}
    \AttributeTok{spp1 =} \FloatTok{0.15}\NormalTok{, }
    \AttributeTok{spp2 =} \FloatTok{0.15}\NormalTok{, }
    \AttributeTok{spp3 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.15}\NormalTok{, .}\DecValTok{5}\NormalTok{, }\DecValTok{1}\NormalTok{),}
    \AttributeTok{spp4 =} \FloatTok{0.1}\NormalTok{, }
    \AttributeTok{spp5 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{),}
    \AttributeTok{spp6 =} \FloatTok{0.25}
\NormalTok{  ),}
  \AttributeTok{nsites =}\NormalTok{ nsites, }
  \AttributeTok{nspecies =}\NormalTok{ nspecies, }
  \AttributeTok{nvisits =}\NormalTok{ nvisits,}
  \AttributeTok{psi =}\NormalTok{ psi, }
  \AttributeTok{lambda =}\NormalTok{ lambda, }
  \AttributeTok{theta =}\NormalTok{ Theta, }
  \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"BySpecies"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\linespread{1}

Note that in contrast with Section \ref{dataSimulation}, \texttt{simulate\_validatedData} expects the \texttt{scenarios} argument to be a list of proportions corresponding to the possible levels of effort for each species when specifying a stratified-by-species design. Internally, \texttt{simulate\_validatedData} calls \texttt{base::expand.grid}, and considers all possible combinations of the various levels of effort for each species, meaning that the number of simulated scenarios grows extremely quickly. The biggest implication of having a larger number of simulation scenarios to consider is increased computation time. For example, in the previous code block we fixed the level of effort for species 1, 2, 4 and 6 at .15, .15, .1, and .25, respectively. There are three possible proportions to validate for species 3 and two possible levels of effort for species 5, yielding six possible scenarios, which are summarized in the additional output \texttt{sim\_data\$scenarios\_df} that is available when \texttt{design\_type\ =\ "BySpecies"} is specified:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(sim\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "full_datasets" "zeros"         "masked_dfs"    "scenarios_df"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_data}\SpecialCharTok{$}\NormalTok{scenarios\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   scenario spp1 spp2 spp3 spp4 spp5 spp6
## 1        1 0.15 0.15 0.15  0.1  0.5 0.25
## 2        2 0.15 0.15 0.50  0.1  0.5 0.25
## 3        3 0.15 0.15 1.00  0.1  0.5 0.25
## 4        4 0.15 0.15 0.15  0.1  1.0 0.25
## 5        5 0.15 0.15 0.50  0.1  1.0 0.25
## 6        6 0.15 0.15 1.00  0.1  1.0 0.25
\end{verbatim}

\linespread{1}

If users would like to supply a tailored set of validation scenarios, this can be done through the \texttt{scen\_expand} and \texttt{scen\_df} arguments as follows:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Define the scenarios dataframe. Each row is a scenario, each column is a spp}
\NormalTok{my\_scenarios }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{spp1 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.05}\NormalTok{, }\FloatTok{0.1}\NormalTok{), }
  \AttributeTok{spp2 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\FloatTok{0.2}\NormalTok{, }\FloatTok{0.3}\NormalTok{),}
  \AttributeTok{spp3 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.2}\NormalTok{, }\FloatTok{0.2}\NormalTok{, }\FloatTok{0.25}\NormalTok{), }
  \AttributeTok{spp4 =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.4}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\FloatTok{0.6}\NormalTok{), }
  \AttributeTok{spp5 =} \FunctionTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{), }
  \AttributeTok{spp6 =} \FunctionTok{rep}\NormalTok{(}\FloatTok{0.5}\NormalTok{, }\DecValTok{3}\NormalTok{)}
\NormalTok{)}

\NormalTok{sim\_data2 }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_validatedData}\NormalTok{(}
  \AttributeTok{n\_datasets =} \DecValTok{10}\NormalTok{, }
  \AttributeTok{design\_type =} \StringTok{"BySpecies"}\NormalTok{,}
  \AttributeTok{scen\_expand =} \ConstantTok{FALSE}\NormalTok{, }
  \AttributeTok{scen\_df =}\NormalTok{ my\_scenarios,}
  \AttributeTok{scenarios =} \ConstantTok{NULL}\NormalTok{,}
  \AttributeTok{nsites =}\NormalTok{ nsites, }
  \AttributeTok{nspecies =}\NormalTok{ nspecies, }
  \AttributeTok{nvisits =}\NormalTok{ nvisits,}
  \AttributeTok{psi =}\NormalTok{ psi, }
  \AttributeTok{lambda =}\NormalTok{ lambda, }
  \AttributeTok{theta =}\NormalTok{ Theta, }
  \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"BySpecies"}\NormalTok{)}
\NormalTok{)}

\NormalTok{sim\_data2}\SpecialCharTok{$}\NormalTok{scenarios\_df }\CommentTok{\# the same as my\_scenarios above}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   scenario spp1 spp2 spp3 spp4 spp5 spp6
## 1        1 0.05  0.1 0.20  0.4    1  0.5
## 2        2 0.05  0.2 0.20  0.5    1  0.5
## 3        3 0.10  0.3 0.25  0.6    1  0.5
\end{verbatim}

\linespread{1}

In the remainder of this example, we use the \texttt{sim\_data} object.
We can combine the \texttt{scenarios\_df} output with the output of \texttt{summarize\_n\_validated} to understand what the scenarios are and how many recordings are validated under each.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{summary1 }\OtherTok{\textless{}{-}}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{scenarios\_df}
\NormalTok{summary2 }\OtherTok{\textless{}{-}} \FunctionTok{summarize\_n\_validated}\NormalTok{(}
\NormalTok{  sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs, }
  \AttributeTok{scenario\_numbers =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \StringTok{"BySpecies"}
\NormalTok{)}

\NormalTok{call\_sum }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(summary1, summary2, }\AttributeTok{by =} \StringTok{"scenario"}\NormalTok{)}

\NormalTok{call\_sum}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   scenario spp1 spp2 spp3 spp4 spp5 spp6 theta_scenario n_selected n_validated
## 1        1 0.15 0.15 0.15  0.1  0.5 0.25      BySpecies      603.8       603.8
## 2        2 0.15 0.15 0.50  0.1  0.5 0.25      BySpecies     1018.3      1018.3
## 3        3 0.15 0.15 1.00  0.1  0.5 0.25      BySpecies     1610.4      1610.4
## 4        4 0.15 0.15 0.15  0.1  1.0 0.25      BySpecies      778.3       778.3
## 5        5 0.15 0.15 0.50  0.1  1.0 0.25      BySpecies     1192.8      1192.8
## 6        6 0.15 0.15 1.00  0.1  1.0 0.25      BySpecies     1784.9      1784.9
\end{verbatim}

\linespread{1}

In the resulting dataframe, we see that scenario 1 has the lowest overall level of validation effort: species 1-3 have 15\% of their recordings validated, species 4 has 10\% validated, species 5 has 50\%, and species 6 has 25\%, yielding around 604 recordings validated in an average dataset. We use one dataset simulated under scenario 1 to tune the MCMC.

\subsection{Tune the MCMC}\label{tune-the-mcmc}

The MCMC tuning in this step is very similar to the procedures used in Section \ref{tune}. We begin by fitting a model to one dataset using the \texttt{tune\_mcmc} function.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(sim\_data}\SpecialCharTok{$}\NormalTok{full\_datasets), }\DecValTok{1}\NormalTok{)}

\NormalTok{tune\_list }\OtherTok{\textless{}{-}} \FunctionTok{tune\_mcmc}\NormalTok{(}
  \AttributeTok{dataset =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs[[}\DecValTok{1}\NormalTok{]][[i]],}
  \AttributeTok{zeros =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros[[i]]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Fitting MCMC in parallel ... this may take a few minutes"
\end{verbatim}

\linespread{1}

As in Section \ref{tune}, we visually inspect the chains for convergence using trace plots. We set trace plot windows to be wider than the suggested values from \texttt{tune\_mcmc}, meaning a lower starting value and a higher ending value. Based on these plots, chains appear to be mixing well as no one chain stands out visually.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 500
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1500
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# increase iters to visualize beyond the warmup and }
\CommentTok{\# iterations output from tune\_mcmc }
\NormalTok{fit }\OtherTok{\textless{}{-}}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{fit}

\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{, }\AttributeTok{window =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{500}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{usingValidationExplorer_files/figure-latex/unnamed-chunk-22-1.pdf}}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"psi"}\NormalTok{, }\AttributeTok{window =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{500}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{usingValidationExplorer_files/figure-latex/unnamed-chunk-23-1.pdf}}

\linespread{1}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mcmc\_trace}\NormalTok{(fit, }\AttributeTok{regex\_pars =} \StringTok{"theta"}\NormalTok{, }\AttributeTok{window =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{500}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{usingValidationExplorer_files/figure-latex/unnamed-chunk-24-1.pdf}}

\linespread{1}

In all trace plots, it appears that MCMC chains have reached approximate convergence well before the warmup value of 500 draws output from \texttt{tune\_mcmc}.

Next, we examine the effective sample sizes in the tails and bulk of the posteriors and the \(\hat{R}\) values:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{MCMC\_diagnostics}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      parameter  ess_bulk  ess_tail     Rhat
## 1    lambda[1]  4747.609  5867.313 1.000828
## 2    lambda[2]  4014.458  5606.669 1.001439
## 3    lambda[3]  4088.549  4595.244 1.000456
## 4    lambda[4]  3251.831  5085.757 1.001154
## 5    lambda[5]  3827.603  5132.476 1.001038
## 6    lambda[6]  3409.017  4641.352 1.000696
## 7       psi[1] 29593.554 29969.577 1.000017
## 8       psi[2] 26159.910 24938.335 1.000115
## 9       psi[3] 29705.484 28178.100 1.000009
## 10      psi[4] 29013.282 29921.387 1.000074
## 11      psi[5] 29584.541 27819.776 1.000069
## 12      psi[6] 24642.370 26651.695 1.000072
## 13 theta[1, 1]  5838.006  8562.459 1.000377
## 14 theta[2, 1]  4094.551  5076.640 1.000683
## 15 theta[3, 1]  4021.544  5905.362 1.000937
## 16 theta[4, 1]  5520.933  7272.689 1.000161
## 17 theta[5, 1]  5132.129  7153.423 1.000849
## 18 theta[6, 1]  3382.287  3430.630 1.000303
## 19 theta[1, 2]  4393.258  6579.509 1.000921
## 20 theta[2, 2]  4932.495  8076.854 1.000855
## 21 theta[3, 2]  5101.804  6419.463 1.000923
## 22 theta[4, 2]  3617.975  4753.040 1.000523
## 23 theta[5, 2]  5771.407  7559.183 1.000103
## 24 theta[6, 2]  3653.652  3153.996 1.001376
## 25 theta[1, 3]  4227.743  4641.658 1.000943
## 26 theta[2, 3]  4314.734  4520.865 1.000164
## 27 theta[3, 3]  5252.021  9697.568 1.000382
## 28 theta[4, 3]  4139.356  5973.868 1.000801
## 29 theta[5, 3]  2521.158  3436.481 1.001166
## 30 theta[6, 3]  4128.737  5297.947 1.000493
## 31 theta[1, 4]  3373.517  3437.188 1.000616
## 32 theta[2, 4]  4180.425  5371.546 1.000342
## 33 theta[3, 4]  3978.870  7768.728 1.000077
## 34 theta[4, 4]  5661.400  7747.385 1.000180
## 35 theta[5, 4]  3809.140  4851.748 1.000690
## 36 theta[6, 4]  4199.286  5284.097 1.000485
## 37 theta[1, 5]  7704.340  9879.655 1.000789
## 38 theta[2, 5]  5999.264  7921.136 1.000174
## 39 theta[3, 5]  2955.866  3530.934 1.004507
## 40 theta[4, 5]  7152.608 10027.420 1.000109
## 41 theta[5, 5]  4942.481  9023.001 1.000321
## 42 theta[6, 5]  5791.689  6980.729 1.000671
## 43 theta[1, 6]  3466.485  3237.729 1.000556
## 44 theta[2, 6]  3436.039  4222.728 1.001604
## 45 theta[3, 6]  5257.353  8456.059 1.000827
## 46 theta[4, 6]  5122.523  6446.945 1.000079
## 47 theta[5, 6]  4362.579  5686.666 1.000689
## 48 theta[6, 6]  4863.504  6855.289 1.000345
\end{verbatim}

\linespread{1}

For all parameters, the bulk and tail effective sample sizes are fairly large: if we slightly decrease the number of post-warmup draws, we could expect to characterize both the center and tails of the posteriors well. Additionally, \(\hat{R} \approx 1.00\) for all parameters, indicating good mixing for chains. As before, we check this suspicion by computing MCMC diagnostic statistics for truncated chains:

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# for each chain, extract iterations 501:2000 for all parameters}
\NormalTok{shortened }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(fit, }\ControlFlowTok{function}\NormalTok{(x) x[(tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup)}\SpecialCharTok{:}\NormalTok{tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{1000}\NormalTok{,])}

\CommentTok{\# summarize the shortened chains and select the effective sample }
\CommentTok{\# size columns}
\FunctionTok{mcmc\_sum}\NormalTok{(shortened, }\AttributeTok{truth =} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(shortened[[}\DecValTok{1}\NormalTok{]]))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(parameter, ess\_bulk, ess\_tail)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      parameter  ess_bulk  ess_tail
## 1    lambda[1]  620.1541  735.0209
## 2    lambda[2]  358.5581  552.5875
## 3    lambda[3]  436.4737  475.7419
## 4    lambda[4]  289.2410  593.6390
## 5    lambda[5]  524.8982  725.3837
## 6    lambda[6]  395.3979  559.5316
## 7       psi[1] 2912.8872 3029.2521
## 8       psi[2] 3071.1906 3123.5393
## 9       psi[3] 2988.4599 2988.9389
## 10      psi[4] 2791.6998 2910.7346
## 11      psi[5] 3119.2375 2951.8337
## 12      psi[6] 2578.2237 2795.6833
## 13 theta[1, 1]  645.5624 1047.8087
## 14 theta[2, 1]  496.2879  803.5267
## 15 theta[3, 1]  407.0094  474.3547
## 16 theta[4, 1]  686.0092 1112.8028
## 17 theta[5, 1]  509.9413  667.9246
## 18 theta[6, 1]  355.7395  285.8066
## 19 theta[1, 2]  399.8220  540.9387
## 20 theta[2, 2]  542.2645 1129.7732
## 21 theta[3, 2]  467.0935  787.4456
## 22 theta[4, 2]  467.6933  570.8157
## 23 theta[5, 2]  507.3923  699.1672
## 24 theta[6, 2]  384.0267  355.3418
## 25 theta[1, 3]  442.1528  467.7336
## 26 theta[2, 3]  503.6549  815.8164
## 27 theta[3, 3]  537.5202 1198.7861
## 28 theta[4, 3]  492.5251  635.0484
## 29 theta[5, 3]  408.8814  583.0683
## 30 theta[6, 3]  478.4605  571.0666
## 31 theta[1, 4]  357.2601  458.8241
## 32 theta[2, 4]  512.6426  619.7832
## 33 theta[3, 4]  401.7507  850.9122
## 34 theta[4, 4]  639.0152 1208.5950
## 35 theta[5, 4]  312.5012  622.5511
## 36 theta[6, 4]  430.8523  489.4023
## 37 theta[1, 5]  970.9268 1249.3867
## 38 theta[2, 5]  519.8450  745.4272
## 39 theta[3, 5]  366.4878  381.8523
## 40 theta[4, 5]  779.8353  830.9113
## 41 theta[5, 5]  582.6914 1065.3185
## 42 theta[6, 5]  683.0759  829.1085
## 43 theta[1, 6]  333.3725  420.2395
## 44 theta[2, 6]  387.5638  300.6319
## 45 theta[3, 6]  538.9592  884.6127
## 46 theta[4, 6]  432.4931  484.8909
## 47 theta[5, 6]  435.3587  561.2244
## 48 theta[6, 6]  444.4765  724.5546
\end{verbatim}

\linespread{1}

The results appear satisfactory, with effective sample sizes of more than 250 in both the tail and bulk of the posterior distributions for each parameter. Based on the results of MCMC exploration, it appears that using an MCMC with 2500 iterations with 500 discarded as warmup is likely to produce good results for our simulation study.

\subsection{Fit models}\label{fit-models}

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sims\_out }\OtherTok{\textless{}{-}} \FunctionTok{run\_sims}\NormalTok{(}
  \AttributeTok{data\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{masked\_dfs,}
  \AttributeTok{zeros\_list =}\NormalTok{ sim\_data}\SpecialCharTok{$}\NormalTok{zeros,}
  \AttributeTok{DGVs =} \FunctionTok{list}\NormalTok{(}\AttributeTok{lambda =}\NormalTok{ lambda, }\AttributeTok{psi =}\NormalTok{ psi, }\AttributeTok{theta =}\NormalTok{ Theta),}
  \AttributeTok{theta\_scenario\_id =} \StringTok{"BySpecies"}\NormalTok{, }
  \AttributeTok{parallel =} \ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{niter =}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{min\_iter }\SpecialCharTok{+} \DecValTok{500}\NormalTok{, }
  \AttributeTok{nburn =}\NormalTok{ tune\_list}\SpecialCharTok{$}\NormalTok{min\_warmup }\SpecialCharTok{+} \DecValTok{250}\NormalTok{,}
  \AttributeTok{thin =} \DecValTok{1}\NormalTok{, }
  \AttributeTok{save\_fits =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{save\_individual\_summaries\_list =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{directory =}\NormalTok{ here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"Vignette"}\NormalTok{, }\StringTok{"BySpecies"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Beginning scenario 1.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 14:50:57.136937
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 2.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 15:07:22.028576
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 3.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 15:31:21.260858
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 4.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 16:08:58.443352
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 5.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 17:12:28.009296
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\begin{verbatim}
## Beginning scenario 6.
\end{verbatim}

\begin{verbatim}
## 2026-03-16 21:13:31.587057
\end{verbatim}

\begin{verbatim}
##   |                                                          |                                                  |   0%  |                                                          |=====                                             |  10%  |                                                          |==========                                        |  20%  |                                                          |===============                                   |  30%  |                                                          |====================                              |  40%  |                                                          |=========================                         |  50%  |                                                          |==============================                    |  60%  |                                                          |===================================               |  70%  |                                                          |========================================          |  80%  |                                                          |=============================================     |  90%  |                                                          |==================================================| 100%
\end{verbatim}

\linespread{1}

The output, \texttt{sims\_out}, will have the same structure as described in Section \ref{runSims}.

\subsection{\texorpdfstring{Visualize results \label{vizbyspp}}{Visualize results }}\label{visualize-results}

Recall that the measurable objectives of our study are to estimate the relative activity rates with estimation error less than 1 call per night and a 95\% posterior interval width of less than 3 calls per night. Furthermore, we assume that the monitoring program can afford to validate 4000 calls in total. All of the possible validation designs shown in \texttt{sim\_data\$scenarios\_df} are feasible given this budget.

We begin with detailed plots of relative activity rates, occurrence probabilities, and classification probabilities.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_out, }
  \AttributeTok{pars =} \StringTok{"lambda"}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \StringTok{"BySpecies"}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{, }
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:vizLamBySpecies}Output from visualize\_parameter\_group under six possible stratified-by-species scenarios for relative activity rates. Parameters are shown in each facet and validation scenario number is on the x-axis. Small grey intervals are 95\% posterior intervals for each parameter from fitted models that converged. Larger colored error bars are average 95\% posterior intervals with the color indicating the coverage. Black dots are the true parameter value and red dots are average posterior means.}]{usingValidationExplorer_files/figure-latex/vizLamBySpecies-1.pdf}}
\caption{\label{fig:vizLamBySpecies}Output from \texttt{visualize\_parameter\_group} under six possible stratified-by-species scenarios for relative activity rates. Parameters are shown in each facet and validation scenario number is on the x-axis. Small grey intervals are 95\% posterior intervals for each parameter from fitted models that converged. Larger colored error bars are average 95\% posterior intervals with the color indicating the coverage. Black dots are the true parameter value and red dots are average posterior means.}
\end{figure}

\linespread{1}

Based on the simulation results shown in Figure \ref{fig:vizLamBySpecies}, any of validation scenarios 1-6 is expected to produce a posterior mean estimate for each relative activity parameter that is near the true value. All models converged for all scenarios. Coverage varies by scenario for each parameter, but recall that we only fit models to 10 datasets.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_out, }
  \AttributeTok{pars =} \StringTok{"psi"}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \StringTok{"BySpecies"}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{, }
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:vizPsiBySpecies}Output from visualize\_parameter\_group under six possible stratified-by-species scenarios for occurrence probabilities. Parameters are shown in each facet and validation scenario number is on the x-axis. Small grey intervals are 95\% posterior intervals for each parameter from fitted models that converged. Larger colored error bars are average 95\% posterior intervals with the color indicating the coverage. Black dots are the true parameter value and red dots are average posterior means.}]{usingValidationExplorer_files/figure-latex/vizPsiBySpecies-1.pdf}}
\caption{\label{fig:vizPsiBySpecies}Output from \texttt{visualize\_parameter\_group} under six possible stratified-by-species scenarios for occurrence probabilities. Parameters are shown in each facet and validation scenario number is on the x-axis. Small grey intervals are 95\% posterior intervals for each parameter from fitted models that converged. Larger colored error bars are average 95\% posterior intervals with the color indicating the coverage. Black dots are the true parameter value and red dots are average posterior means.}
\end{figure}

\linespread{1}

The simulation results for occurrence probabilities show a small amount estimation error for all occurrence probabilities, with the size and direction varying depending on the species. For species with larger estimation error, coverage is also slightly low. However, since we are most concerned with relative activity, the goal is to check results for each \(\psi_k\) for severe estimation error and/or lack of coverage, which are not shown in Figure \ref{fig:vizPsiBySpecies}. Similarly, we do not observe alarming results in Figure \ref{fig:vizThetaBySpecies}.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{visualize\_parameter\_group}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_out, }
  \AttributeTok{pars =} \StringTok{"theta"}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \StringTok{"BySpecies"}\NormalTok{, }
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{, }
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:vizThetaBySpecies}Output from visualize\_parameter\_group under six possible stratified-by-species scenarios for classification probabilities. Parameters are shown in each facet and validation scenario number is on the x-axis. Small grey intervals are 95\% posterior intervals for each parameter from fitted models that converged. Larger colored error bars are average 95\% posterior intervals with the color indicating the coverage. Black dots are the true parameter value and red dots are average posterior means.}]{usingValidationExplorer_files/figure-latex/vizThetaBySpecies-1.pdf}}
\caption{\label{fig:vizThetaBySpecies}Output from \texttt{visualize\_parameter\_group} under six possible stratified-by-species scenarios for classification probabilities. Parameters are shown in each facet and validation scenario number is on the x-axis. Small grey intervals are 95\% posterior intervals for each parameter from fitted models that converged. Larger colored error bars are average 95\% posterior intervals with the color indicating the coverage. Black dots are the true parameter value and red dots are average posterior means.}
\end{figure}

\linespread{1}

One measurable objective is for 95\% posterior interval widths to be less than 3 calls per night for each species' relative activity rate. As in Section \ref{viz}, the \texttt{plot\_width\_vs\_calls} function provides Figure \ref{fig:widthVscalls}, which addresses this measurable objective directly.

\linespread{1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_width\_vs\_calls}\NormalTok{(}
  \AttributeTok{sim\_summary =}\NormalTok{ sims\_out, }
  \AttributeTok{calls\_summary =}\NormalTok{ call\_sum, }
  \AttributeTok{regex\_pars =} \StringTok{"lambda"}\NormalTok{,}
  \AttributeTok{theta\_scenario =} \FunctionTok{unique}\NormalTok{(sims\_out}\SpecialCharTok{$}\NormalTok{theta\_scenario),}
  \AttributeTok{scenarios =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{,}
  \AttributeTok{max\_calls =} \DecValTok{1000} \CommentTok{\# put shading over scenarios that are beyond budget}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:widthVscalls}Plots of 95\% posterior interval width vs the number of calls validated.}]{usingValidationExplorer_files/figure-latex/widthVscalls-1.pdf}}
\caption{\label{fig:widthVscalls}Plots of 95\% posterior interval width vs the number of calls validated.}
\end{figure}

\linespread{1}

Once again as in Section \ref{viz}, the widest posterior interval width is for species 5. All validation scenarios have average 95\% posterior interval widths near or slightly below 3 calls per night, but the error bars indicate an interval width greater than 3 is possible for any validation scenario. Scenario 6, in which 1785 recordings are validated, has the narrowest expected interval width.

\subsection{\texorpdfstring{Take-aways \label{takeaway-bySpp}}{Take-aways }}\label{take-aways}

The results in Section \ref{vizbyspp}, imply that, of the stratified-by-species validation designs considered, scenario 6 offered the best results with respect to the measurable objectives we outlined in Section \ref{MO}. In this scenario, the six species in our assemblage receive 15\%, 15\%, 100\%, 10\%, 100\%, and 25\% of their recordings validated, respectively.

To keep the number of scenarios in this example small, we fixed the LOVE for several species. However, if the measurable objectives specified the desired accuracy and precision for estimates of occurrence probability, it may be desirable to consider alternative validation scenarios. For example, we consistently underestimated the occurrence probability for species 6 (Figure \ref{fig:vizPsiBySpecies}), and additional simulations under validation designs that varied the level of effort for species 6 would be warranted if measurable objectives related to occurrence probability for this species.

\section{Conclusion}\label{conclusion}

We have demonstrated the use of the \texttt{ValidationExplorer} package when the objective is to compare the merits of four competing LOVEs for fixed-effort and stratified-by-species designs. Specifically, in the fixed-effort design we considered validating a random sample of 5\%, 10\%, 15\% or 30\% of the recordings obtained during each visit to each site. In the stratified-by-species designs, we considered a suite of validation designs, fixing effort for species 1,2, 4, and 6 at less than or equal to 25\%, and varied the level of effort for species 3 and 5. The exact simulations considered are summarized in the \texttt{call\_sum} object in Section \ref{simBySpp}. The measurable objectives outlined in Section \ref{MO} were to estimate the relative activity parameters for each species, with near-nominal coverage and width less than 3 calls per night for 95\% posterior intervals. Results, and their implications for these measurable objectives were summarized in Sections \ref{takeaway-FE} and \ref{takeaway-bySpp}. Practitioners who would like to inform study design prior to data collection can repeat multiple simulation studies to see how inferences change with the number of sites and balanced visits, in addition to the validation design.

\newpage

\section{\texorpdfstring{Table of Functions \label{BigTable}}{Table of Functions }}\label{table-of-functions}

\singlespacing
\begin{longtable}{p{0.27\linewidth}p{0.32\linewidth}p{0.33\linewidth}}
    \toprule
        Function & Argument & Description   \\
        \midrule
        
        \texttt{simulate\textunderscore validatedData} &  \texttt{n\textunderscore datasets} & The number of datasets to be simulated \\ 
        \addlinespace
        & \texttt{design\textunderscore type} & The type of validation design. Must be one of \texttt{"BySpecies"} or \texttt{"FixedPercent"} \\ 
        \addlinespace
        & \texttt{scenarios} & The possible levels of effort. If \texttt{design\textunderscore type = "BySpecies"}, this is provided as a list with vector-valued entries containing the possible percentages to validate for each species. If \texttt{design\textunderscore type = "FixedPercent"}, this argument is a vector of possible percentages. \\ 
        \addlinespace
        & \texttt{n\textunderscore sites, n\textunderscore visits, n\textunderscore species} & The number of sites, visits and species in the assemblage \\ 
        \addlinespace
        & \texttt{psi, lambda, theta},  & Vectors of length \texttt{nspecies} containing the the parameter values for each species \\ 
        \addlinespace
        & \texttt{directory} & The working directory where datasets are to be saved if the following arguments are set to TRUE \\
        \addlinespace
        & \texttt{save\textunderscore datasets, save\textunderscore masked_datasets} & Logicals indicating whether to save each type of dataset \\
        \addlinespace

        \hline
        \texttt{summarize\textunderscore n\textunderscore validated} & \texttt{data\textunderscore list} & A list of simulated (masked) datasets output from \texttt{simulate\textunderscore validatedData} \\ 
        \addlinespace 
        & \texttt{zeros\textunderscore list} & A list of true species/autoID combinations that were never observed at each site-visit. \\ 
        \addlinespace
        & \texttt{theta\textunderscore scenario} & An optional character string identifying the classifier scenario. If output from \texttt{summarize\textunderscore n\textunderscore validated} is to be used with any of the \texttt{plot\textunderscore X\textunderscore vs\textunderscore calls} functions described below, this string must match the \texttt{theta\textunderscore scenario\textunderscore id} argument supplied to \texttt{run\textunderscore sims}. \\
        \addlinespace

        \hline
        \texttt{run\textunderscore sims} & \texttt{data\textunderscore list} & A nested list of masked datasets in the format output from \texttt{simualate\textunderscore validatedData}. The first layer of the list corresponds to scenarios, with each entry containing a list of \texttt{n\textunderscore datasets} validated according to the scenario. \\ 
        \addlinespace
        & \texttt{zeros\textunderscore list} & A list of length \texttt{n\textunderscore datasets} containing the site-visit-true-autoID combinations that were never observed. \\ 
        \addlinespace 
        & \texttt{DGVs} & A named list of the true data-generating values with entries \texttt{"psi", "lambda"} and \texttt{"theta"}. \\ 
        \addlinespace
        & \texttt{theta\textunderscore scenario\textunderscore id} & An ID to show which classifier the scenario is under. This is provided as a convenience for the user if multiple simulation studies are to be conducted.\\
        \addlinespace
        & \texttt{parallel} &  A logical indicating whether MCMC sampling should be fit in parallel (default setting is TRUE). If you have many datasets and many scenarios, we recommend this setting. \\
        \addlinespace
        & \texttt{n\textunderscore iter, nburn, thin} &  The number of iterations, warmup and thinning interval for each chain in the MCMC. Default values are 2000, 1000, and 1, respectively. \\ 
        \addlinespace
        & \texttt{save\textunderscore fits} &  A logical denoting whether or not to save the draws from individual fitted models. If TRUE, you must have the file structure described in Step 2. Fits will be saved as RDS objects that can be read in later. Default value is FALSE.\\
        \addlinespace
        & \texttt{save\textunderscore individual\textunderscore summaries\textunderscore list} & A logical indicating whether to save individual summary lists that are output after each validation scenario. Default value is FALSE.\\ 
        \addlinespace
        & \texttt{directory} &  Where to save fits and summaries. Required if \texttt{save\textunderscore fits\ =\ TRUE} or \texttt{save\textunderscore individual\textunderscore summaries\textunderscore list\ =\ TRUE}. Default value is the current working directory given by \texttt{here::here()} \\ 
        \addlinespace 

        \hline
    
        \texttt{visualize\textunderscore parameter\textunderscore group} & \texttt{sim\textunderscore summary} & A dataframe in the format of the summaries output by \texttt{run\textunderscore sims}. Column names must match those of the \texttt{run\textunderscore sims} output. \\ 
        \addlinespace 
        & \texttt{pars} & The name of the parameter ``group'' to be visualized (e.g, \texttt{"psi"}, \texttt{"lambda"} or \texttt{"theta"}). \\ 
        \addlinespace 
        & \texttt{theta\textunderscore scenario}&  The \(\Theta\) classifier ID. \\ 
        \addlinespace 
        & \texttt{scenarios} &  Which scenarios to visualize? \\ 
        \addlinespace 
        & \texttt{convergence\textunderscore threshold}& What value should $\hat{R}$ be below to be considered ``converged''? Default value is 1.1. This value matters because only model fits where all parameter values are below the \texttt{convergence\textunderscore threshold} are used for visualization. \\ 
        \addlinespace 
        
        \hline
        \texttt{visualize\textunderscore single\textunderscore parameter} & & Arguments are identical to  \texttt{visualize\textunderscore parameter\textunderscore group} \\ 
        \addlinespace
        
        \hline 
        
        \texttt{plot_bias_vs_calls}, \texttt{plot_coverage_vs_calls}, \texttt{plot_width_vs_calls} & \texttt{sims_summary} & The summary output in the format from \texttt{run\textunderscore sims} \\ 
        \addlinespace
        & \texttt{calls\textunderscore summary} & A summary of the number of calls validated per scenario. Expected format is that of output from \texttt{summarize\textunderscore n\textunderscore validated}. \\ 
        \addlinespace
        & \texttt{pars} & The parameters to visualize. \\ 
        \addlinespace
        & \texttt{regex\textunderscore pars} & A group of parameters to visualize. One of \texttt{"psi"}, \texttt{"lambda"} or \texttt{"theta"}. \\ 
        \addlinespace
        & \texttt{theta\textunderscore scenario} & The classifier scenario ID. \\
        \addlinespace
        & \texttt{scenarios} & The scenarios to be compared. \\
        \addlinespace
        & \texttt{convergence\textunderscore threshold} & At what value is an MCMC algorithm considered ``converged"? \\ 
        \addlinespace
        \bottomrule
    \caption{Argument descriptions for each function in the \texttt{ValidationExplorer} software. My hope is that in the eventual final paper, this will be a scrollable html table}
    \label{tab:my_label}
\end{longtable}

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-bayesplot}
Gabry, Jonah, Daniel Simpson, Aki Vehtari, Michael Betancourt, and Andrew Gelman. 2019. {``Visualization in Bayesian Workflow.''} \emph{J. R. Stat. Soc. A} 182: 389--402. \url{https://doi.org/10.1111/rssa.12378}.

\bibitem[\citeproctext]{ref-loeb15}
Loeb, Susan C., Thomas J. Rodhouse, Laura E. Ellison, et al. 2015. \emph{A Plan for the {N}orth {A}merican Bat Monitoring Program ({NAB}at)}. SRS-208. USDA Forest Service.

\bibitem[\citeproctext]{ref-stratton22}
Stratton, Christian, Kathryn M. Irvine, Katharine M. Banner, Wilson J. Wright, Cori Lausen, and Jason Rae. 2022. {``Coupling Validation Effort with in Situ Bioacoustic Data Improves Estimating Relative Activity and Occupancy for Multiple Species with Cross-Species Misclassifications.''} \emph{Methods in Ecology and Evolution} 13 (6): 1288--303. https://doi.org/\url{https://doi.org/10.1111/2041-210X.13831}.

\end{CSLReferences}

\end{document}
